// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package platformdb

import (
	"context"
)

const ListEnabledServiceCatalog = `-- name: ListEnabledServiceCatalog :many
SELECT service_id,
    display_name,
    upstream_service_name,
    transport_type,
    internal_port,
    public_path,
    internal_upstream_path,
    health_path,
    health_probe_expectation,
    resource_profile,
    persistence_policy,
    adapter_requirement,
    secret_contract,
    enabled,
    created_at,
    updated_at
FROM service_catalog
WHERE enabled = 1
ORDER BY service_id
`

// ListEnabledServiceCatalog
//
//	SELECT service_id,
//	    display_name,
//	    upstream_service_name,
//	    transport_type,
//	    internal_port,
//	    public_path,
//	    internal_upstream_path,
//	    health_path,
//	    health_probe_expectation,
//	    resource_profile,
//	    persistence_policy,
//	    adapter_requirement,
//	    secret_contract,
//	    enabled,
//	    created_at,
//	    updated_at
//	FROM service_catalog
//	WHERE enabled = 1
//	ORDER BY service_id
func (q *Queries) ListEnabledServiceCatalog(ctx context.Context) ([]ServiceCatalog, error) {
	rows, err := q.db.QueryContext(ctx, ListEnabledServiceCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCatalog{}
	for rows.Next() {
		var i ServiceCatalog
		if err := rows.Scan(
			&i.ServiceID,
			&i.DisplayName,
			&i.UpstreamServiceName,
			&i.TransportType,
			&i.InternalPort,
			&i.PublicPath,
			&i.InternalUpstreamPath,
			&i.HealthPath,
			&i.HealthProbeExpectation,
			&i.ResourceProfile,
			&i.PersistencePolicy,
			&i.AdapterRequirement,
			&i.SecretContract,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertServiceCatalogEntry = `-- name: UpsertServiceCatalogEntry :exec
INSERT INTO service_catalog (
    service_id,
    display_name,
    upstream_service_name,
    transport_type,
    internal_port,
    public_path,
    internal_upstream_path,
    health_path,
    health_probe_expectation,
    resource_profile,
    persistence_policy,
    adapter_requirement,
    secret_contract,
    enabled,
    updated_at
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    CURRENT_TIMESTAMP
)
ON CONFLICT(service_id) DO UPDATE SET
    display_name = excluded.display_name,
    upstream_service_name = excluded.upstream_service_name,
    transport_type = excluded.transport_type,
    internal_port = excluded.internal_port,
    public_path = excluded.public_path,
    internal_upstream_path = excluded.internal_upstream_path,
    health_path = excluded.health_path,
    health_probe_expectation = excluded.health_probe_expectation,
    resource_profile = excluded.resource_profile,
    persistence_policy = excluded.persistence_policy,
    adapter_requirement = excluded.adapter_requirement,
    secret_contract = excluded.secret_contract,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertServiceCatalogEntryParams struct {
	ServiceID              string `db:"service_id" json:"service_id"`
	DisplayName            string `db:"display_name" json:"display_name"`
	UpstreamServiceName    string `db:"upstream_service_name" json:"upstream_service_name"`
	TransportType          string `db:"transport_type" json:"transport_type"`
	InternalPort           int64  `db:"internal_port" json:"internal_port"`
	PublicPath             string `db:"public_path" json:"public_path"`
	InternalUpstreamPath   string `db:"internal_upstream_path" json:"internal_upstream_path"`
	HealthPath             string `db:"health_path" json:"health_path"`
	HealthProbeExpectation string `db:"health_probe_expectation" json:"health_probe_expectation"`
	ResourceProfile        string `db:"resource_profile" json:"resource_profile"`
	PersistencePolicy      string `db:"persistence_policy" json:"persistence_policy"`
	AdapterRequirement     string `db:"adapter_requirement" json:"adapter_requirement"`
	SecretContract         string `db:"secret_contract" json:"secret_contract"`
	Enabled                int64  `db:"enabled" json:"enabled"`
}

// UpsertServiceCatalogEntry
//
//	INSERT INTO service_catalog (
//	    service_id,
//	    display_name,
//	    upstream_service_name,
//	    transport_type,
//	    internal_port,
//	    public_path,
//	    internal_upstream_path,
//	    health_path,
//	    health_probe_expectation,
//	    resource_profile,
//	    persistence_policy,
//	    adapter_requirement,
//	    secret_contract,
//	    enabled,
//	    updated_at
//	)
//	VALUES (
//	    ?1,
//	    ?2,
//	    ?3,
//	    ?4,
//	    ?5,
//	    ?6,
//	    ?7,
//	    ?8,
//	    ?9,
//	    ?10,
//	    ?11,
//	    ?12,
//	    ?13,
//	    ?14,
//	    CURRENT_TIMESTAMP
//	)
//	ON CONFLICT(service_id) DO UPDATE SET
//	    display_name = excluded.display_name,
//	    upstream_service_name = excluded.upstream_service_name,
//	    transport_type = excluded.transport_type,
//	    internal_port = excluded.internal_port,
//	    public_path = excluded.public_path,
//	    internal_upstream_path = excluded.internal_upstream_path,
//	    health_path = excluded.health_path,
//	    health_probe_expectation = excluded.health_probe_expectation,
//	    resource_profile = excluded.resource_profile,
//	    persistence_policy = excluded.persistence_policy,
//	    adapter_requirement = excluded.adapter_requirement,
//	    secret_contract = excluded.secret_contract,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertServiceCatalogEntry(ctx context.Context, arg UpsertServiceCatalogEntryParams) error {
	_, err := q.db.ExecContext(ctx, UpsertServiceCatalogEntry,
		arg.ServiceID,
		arg.DisplayName,
		arg.UpstreamServiceName,
		arg.TransportType,
		arg.InternalPort,
		arg.PublicPath,
		arg.InternalUpstreamPath,
		arg.HealthPath,
		arg.HealthProbeExpectation,
		arg.ResourceProfile,
		arg.PersistencePolicy,
		arg.AdapterRequirement,
		arg.SecretContract,
		arg.Enabled,
	)
	return err
}
