// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: controlplane.sql

package platformdb

import (
	"context"
	"database/sql"
	"strings"
)

const CountSubjectServiceGrant = `-- name: CountSubjectServiceGrant :one
SELECT COUNT(*)
FROM service_grants
JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
WHERE service_grants.subject_sub = ?1
  AND service_grants.service_id = ?2
  AND service_catalog.enabled = 1
`

type CountSubjectServiceGrantParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
	ServiceID  string `db:"service_id" json:"service_id"`
}

// CountSubjectServiceGrant
//
//	SELECT COUNT(*)
//	FROM service_grants
//	JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
//	WHERE service_grants.subject_sub = ?1
//	  AND service_grants.service_id = ?2
//	  AND service_catalog.enabled = 1
func (q *Queries) CountSubjectServiceGrant(ctx context.Context, arg CountSubjectServiceGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSubjectServiceGrant, arg.SubjectSub, arg.ServiceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteAllServiceGrants = `-- name: DeleteAllServiceGrants :exec
DELETE FROM service_grant_sources WHERE source_group <> 'manual'
`

// DeleteAllServiceGrants
//
//	DELETE FROM service_grant_sources WHERE source_group <> 'manual'
func (q *Queries) DeleteAllServiceGrants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllServiceGrants)
	return err
}

const DeleteManualServiceGrantSource = `-- name: DeleteManualServiceGrantSource :exec
DELETE FROM service_grant_sources
WHERE subject_sub = ?1
  AND service_id = ?2
  AND source_group = 'manual'
`

type DeleteManualServiceGrantSourceParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
	ServiceID  string `db:"service_id" json:"service_id"`
}

// DeleteManualServiceGrantSource
//
//	DELETE FROM service_grant_sources
//	WHERE subject_sub = ?1
//	  AND service_id = ?2
//	  AND source_group = 'manual'
func (q *Queries) DeleteManualServiceGrantSource(ctx context.Context, arg DeleteManualServiceGrantSourceParams) error {
	_, err := q.db.ExecContext(ctx, DeleteManualServiceGrantSource, arg.SubjectSub, arg.ServiceID)
	return err
}

const DeleteStaleServiceGrants = `-- name: DeleteStaleServiceGrants :exec
DELETE FROM service_grant_sources
WHERE source_group <> 'manual'
  AND subject_sub NOT IN (/*SLICE:subject_subs*/?)
`

type DeleteStaleServiceGrantsParams struct {
	SubjectSubs []string `db:"subject_subs" json:"subject_subs"`
}

// DeleteStaleServiceGrants
//
//	DELETE FROM service_grant_sources
//	WHERE source_group <> 'manual'
//	  AND subject_sub NOT IN (/*SLICE:subject_subs*/?)
func (q *Queries) DeleteStaleServiceGrants(ctx context.Context, arg DeleteStaleServiceGrantsParams) error {
	query := DeleteStaleServiceGrants
	var queryParams []interface{}
	if len(arg.SubjectSubs) > 0 {
		for _, v := range arg.SubjectSubs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:subject_subs*/?", strings.Repeat(",?", len(arg.SubjectSubs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:subject_subs*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const DeleteSubjectGrantSources = `-- name: DeleteSubjectGrantSources :exec
DELETE FROM service_grant_sources WHERE subject_sub = ?1
`

type DeleteSubjectGrantSourcesParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
}

// DeleteSubjectGrantSources
//
//	DELETE FROM service_grant_sources WHERE subject_sub = ?1
func (q *Queries) DeleteSubjectGrantSources(ctx context.Context, arg DeleteSubjectGrantSourcesParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSubjectGrantSources, arg.SubjectSub)
	return err
}

const DeleteSubjectGrants = `-- name: DeleteSubjectGrants :exec
DELETE FROM service_grants WHERE subject_sub = ?1
`

type DeleteSubjectGrantsParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
}

// DeleteSubjectGrants
//
//	DELETE FROM service_grants WHERE subject_sub = ?1
func (q *Queries) DeleteSubjectGrants(ctx context.Context, arg DeleteSubjectGrantsParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSubjectGrants, arg.SubjectSub)
	return err
}

const DeleteSubjectSyncedGrantSources = `-- name: DeleteSubjectSyncedGrantSources :exec
DELETE FROM service_grant_sources
WHERE subject_sub = ?1
  AND source_group <> 'manual'
`

type DeleteSubjectSyncedGrantSourcesParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
}

// DeleteSubjectSyncedGrantSources
//
//	DELETE FROM service_grant_sources
//	WHERE subject_sub = ?1
//	  AND source_group <> 'manual'
func (q *Queries) DeleteSubjectSyncedGrantSources(ctx context.Context, arg DeleteSubjectSyncedGrantSourcesParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSubjectSyncedGrantSources, arg.SubjectSub)
	return err
}

const DeleteTenantInstance = `-- name: DeleteTenantInstance :exec
DELETE FROM tenant_instances WHERE tenant_id = ?1
`

type DeleteTenantInstanceParams struct {
	TenantID []byte `db:"tenant_id" json:"tenant_id"`
}

// DeleteTenantInstance
//
//	DELETE FROM tenant_instances WHERE tenant_id = ?1
func (q *Queries) DeleteTenantInstance(ctx context.Context, arg DeleteTenantInstanceParams) error {
	_, err := q.db.ExecContext(ctx, DeleteTenantInstance, arg.TenantID)
	return err
}

const EnableTenantInstance = `-- name: EnableTenantInstance :exec
UPDATE tenant_instances
SET subject_key = ?1,
    tenant_instance_name = ?2,
    internal_dns_name = ?3,
    desired_state = ?4,
    runtime_state = ?5,
    last_error = NULLIF(?6, ''),
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?7
`

type EnableTenantInstanceParams struct {
	SubjectKey         string      `db:"subject_key" json:"subject_key"`
	TenantInstanceName string      `db:"tenant_instance_name" json:"tenant_instance_name"`
	InternalDnsName    string      `db:"internal_dns_name" json:"internal_dns_name"`
	DesiredState       string      `db:"desired_state" json:"desired_state"`
	RuntimeState       string      `db:"runtime_state" json:"runtime_state"`
	LastError          interface{} `db:"last_error" json:"last_error"`
	TenantID           []byte      `db:"tenant_id" json:"tenant_id"`
}

// EnableTenantInstance
//
//	UPDATE tenant_instances
//	SET subject_key = ?1,
//	    tenant_instance_name = ?2,
//	    internal_dns_name = ?3,
//	    desired_state = ?4,
//	    runtime_state = ?5,
//	    last_error = NULLIF(?6, ''),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?7
func (q *Queries) EnableTenantInstance(ctx context.Context, arg EnableTenantInstanceParams) error {
	_, err := q.db.ExecContext(ctx, EnableTenantInstance,
		arg.SubjectKey,
		arg.TenantInstanceName,
		arg.InternalDnsName,
		arg.DesiredState,
		arg.RuntimeState,
		arg.LastError,
		arg.TenantID,
	)
	return err
}

const GetSubject = `-- name: GetSubject :one
SELECT subject_sub,
       subject_key,
       preferred_username,
       email,
       display_name,
       account_binding_id,
       account_binding_claim
FROM subjects
WHERE subject_sub = ?1
`

type GetSubjectParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
}

type GetSubjectRow struct {
	SubjectSub          string         `db:"subject_sub" json:"subject_sub"`
	SubjectKey          string         `db:"subject_key" json:"subject_key"`
	PreferredUsername   sql.NullString `db:"preferred_username" json:"preferred_username"`
	Email               sql.NullString `db:"email" json:"email"`
	DisplayName         sql.NullString `db:"display_name" json:"display_name"`
	AccountBindingID    sql.NullString `db:"account_binding_id" json:"account_binding_id"`
	AccountBindingClaim sql.NullString `db:"account_binding_claim" json:"account_binding_claim"`
}

// GetSubject
//
//	SELECT subject_sub,
//	       subject_key,
//	       preferred_username,
//	       email,
//	       display_name,
//	       account_binding_id,
//	       account_binding_claim
//	FROM subjects
//	WHERE subject_sub = ?1
func (q *Queries) GetSubject(ctx context.Context, arg GetSubjectParams) (GetSubjectRow, error) {
	row := q.db.QueryRowContext(ctx, GetSubject, arg.SubjectSub)
	var i GetSubjectRow
	err := row.Scan(
		&i.SubjectSub,
		&i.SubjectKey,
		&i.PreferredUsername,
		&i.Email,
		&i.DisplayName,
		&i.AccountBindingID,
		&i.AccountBindingClaim,
	)
	return i, err
}

const InsertEffectiveServiceGrantsFromSources = `-- name: InsertEffectiveServiceGrantsFromSources :exec
INSERT INTO service_grants (subject_sub, service_id, source_group, granted_at, last_synced_at)
SELECT subject_sub,
       service_id,
       CASE WHEN SUM(CASE WHEN source_group = 'manual' THEN 1 ELSE 0 END) > 0 THEN 'manual' ELSE MIN(source_group) END AS source_group,
       MIN(granted_at) AS granted_at,
       MAX(last_synced_at) AS last_synced_at
FROM service_grant_sources
GROUP BY subject_sub, service_id
`

// InsertEffectiveServiceGrantsFromSources
//
//	INSERT INTO service_grants (subject_sub, service_id, source_group, granted_at, last_synced_at)
//	SELECT subject_sub,
//	       service_id,
//	       CASE WHEN SUM(CASE WHEN source_group = 'manual' THEN 1 ELSE 0 END) > 0 THEN 'manual' ELSE MIN(source_group) END AS source_group,
//	       MIN(granted_at) AS granted_at,
//	       MAX(last_synced_at) AS last_synced_at
//	FROM service_grant_sources
//	GROUP BY subject_sub, service_id
func (q *Queries) InsertEffectiveServiceGrantsFromSources(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, InsertEffectiveServiceGrantsFromSources)
	return err
}

const InsertReconcileRun = `-- name: InsertReconcileRun :exec
INSERT INTO reconcile_runs (run_id, tenant_id, desired_state, observed_state, action, status, details, started_at, finished_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertReconcileRunParams struct {
	RunID         []byte         `db:"run_id" json:"run_id"`
	TenantID      []byte         `db:"tenant_id" json:"tenant_id"`
	DesiredState  string         `db:"desired_state" json:"desired_state"`
	ObservedState sql.NullString `db:"observed_state" json:"observed_state"`
	Action        string         `db:"action" json:"action"`
	Status        string         `db:"status" json:"status"`
	Details       string         `db:"details" json:"details"`
	StartedAt     string         `db:"started_at" json:"started_at"`
	FinishedAt    sql.NullString `db:"finished_at" json:"finished_at"`
}

// InsertReconcileRun
//
//	INSERT INTO reconcile_runs (run_id, tenant_id, desired_state, observed_state, action, status, details, started_at, finished_at)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
func (q *Queries) InsertReconcileRun(ctx context.Context, arg InsertReconcileRunParams) error {
	_, err := q.db.ExecContext(ctx, InsertReconcileRun,
		arg.RunID,
		arg.TenantID,
		arg.DesiredState,
		arg.ObservedState,
		arg.Action,
		arg.Status,
		arg.Details,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const InsertServiceGrantSource = `-- name: InsertServiceGrantSource :exec
INSERT INTO service_grant_sources (subject_sub, service_id, source_group, granted_at, last_synced_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(subject_sub, service_id, source_group) DO UPDATE SET
    last_synced_at = excluded.last_synced_at,
    updated_at = CURRENT_TIMESTAMP
`

type InsertServiceGrantSourceParams struct {
	SubjectSub   string `db:"subject_sub" json:"subject_sub"`
	ServiceID    string `db:"service_id" json:"service_id"`
	SourceGroup  string `db:"source_group" json:"source_group"`
	GrantedAt    string `db:"granted_at" json:"granted_at"`
	LastSyncedAt string `db:"last_synced_at" json:"last_synced_at"`
}

// InsertServiceGrantSource
//
//	INSERT INTO service_grant_sources (subject_sub, service_id, source_group, granted_at, last_synced_at)
//	VALUES (?1, ?2, ?3, ?4, ?5)
//	ON CONFLICT(subject_sub, service_id, source_group) DO UPDATE SET
//	    last_synced_at = excluded.last_synced_at,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) InsertServiceGrantSource(ctx context.Context, arg InsertServiceGrantSourceParams) error {
	_, err := q.db.ExecContext(ctx, InsertServiceGrantSource,
		arg.SubjectSub,
		arg.ServiceID,
		arg.SourceGroup,
		arg.GrantedAt,
		arg.LastSyncedAt,
	)
	return err
}

const InsertTenantInstance = `-- name: InsertTenantInstance :exec
INSERT INTO tenant_instances (tenant_id, subject_sub, service_id, subject_key, tenant_instance_name, internal_dns_name, desired_state, runtime_state)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertTenantInstanceParams struct {
	TenantID           []byte `db:"tenant_id" json:"tenant_id"`
	SubjectSub         string `db:"subject_sub" json:"subject_sub"`
	ServiceID          string `db:"service_id" json:"service_id"`
	SubjectKey         string `db:"subject_key" json:"subject_key"`
	TenantInstanceName string `db:"tenant_instance_name" json:"tenant_instance_name"`
	InternalDnsName    string `db:"internal_dns_name" json:"internal_dns_name"`
	DesiredState       string `db:"desired_state" json:"desired_state"`
	RuntimeState       string `db:"runtime_state" json:"runtime_state"`
}

// InsertTenantInstance
//
//	INSERT INTO tenant_instances (tenant_id, subject_sub, service_id, subject_key, tenant_instance_name, internal_dns_name, desired_state, runtime_state)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
func (q *Queries) InsertTenantInstance(ctx context.Context, arg InsertTenantInstanceParams) error {
	_, err := q.db.ExecContext(ctx, InsertTenantInstance,
		arg.TenantID,
		arg.SubjectSub,
		arg.ServiceID,
		arg.SubjectKey,
		arg.TenantInstanceName,
		arg.InternalDnsName,
		arg.DesiredState,
		arg.RuntimeState,
	)
	return err
}

const ListDesiredTenantSpecs = `-- name: ListDesiredTenantSpecs :many
SELECT subjects.subject_sub,
       subjects.subject_key,
       COALESCE(subjects.preferred_username, '') AS preferred_username,
       COALESCE(subjects.email, '') AS email,
       COALESCE(subjects.display_name, '') AS display_name,
       COALESCE(subjects.account_binding_id, '') AS account_binding_id,
       COALESCE(subjects.account_binding_claim, '') AS account_binding_claim,
       service_grants.service_id
FROM service_grants
JOIN subjects ON subjects.subject_sub = service_grants.subject_sub
JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
WHERE service_catalog.enabled = 1
ORDER BY service_grants.service_id, subjects.subject_sub
`

type ListDesiredTenantSpecsRow struct {
	SubjectSub          string `db:"subject_sub" json:"subject_sub"`
	SubjectKey          string `db:"subject_key" json:"subject_key"`
	PreferredUsername   string `db:"preferred_username" json:"preferred_username"`
	Email               string `db:"email" json:"email"`
	DisplayName         string `db:"display_name" json:"display_name"`
	AccountBindingID    string `db:"account_binding_id" json:"account_binding_id"`
	AccountBindingClaim string `db:"account_binding_claim" json:"account_binding_claim"`
	ServiceID           string `db:"service_id" json:"service_id"`
}

// ListDesiredTenantSpecs
//
//	SELECT subjects.subject_sub,
//	       subjects.subject_key,
//	       COALESCE(subjects.preferred_username, '') AS preferred_username,
//	       COALESCE(subjects.email, '') AS email,
//	       COALESCE(subjects.display_name, '') AS display_name,
//	       COALESCE(subjects.account_binding_id, '') AS account_binding_id,
//	       COALESCE(subjects.account_binding_claim, '') AS account_binding_claim,
//	       service_grants.service_id
//	FROM service_grants
//	JOIN subjects ON subjects.subject_sub = service_grants.subject_sub
//	JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
//	WHERE service_catalog.enabled = 1
//	ORDER BY service_grants.service_id, subjects.subject_sub
func (q *Queries) ListDesiredTenantSpecs(ctx context.Context) ([]ListDesiredTenantSpecsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDesiredTenantSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDesiredTenantSpecsRow{}
	for rows.Next() {
		var i ListDesiredTenantSpecsRow
		if err := rows.Scan(
			&i.SubjectSub,
			&i.SubjectKey,
			&i.PreferredUsername,
			&i.Email,
			&i.DisplayName,
			&i.AccountBindingID,
			&i.AccountBindingClaim,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSubjectServiceGrants = `-- name: ListSubjectServiceGrants :many
SELECT service_grants.subject_sub,
       service_grants.service_id,
       service_grants.source_group,
       service_grants.granted_at,
       service_grants.last_synced_at
FROM service_grants
JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
WHERE service_grants.subject_sub = ?1
  AND service_catalog.enabled = 1
ORDER BY service_grants.service_id
`

type ListSubjectServiceGrantsParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
}

type ListSubjectServiceGrantsRow struct {
	SubjectSub   string `db:"subject_sub" json:"subject_sub"`
	ServiceID    string `db:"service_id" json:"service_id"`
	SourceGroup  string `db:"source_group" json:"source_group"`
	GrantedAt    string `db:"granted_at" json:"granted_at"`
	LastSyncedAt string `db:"last_synced_at" json:"last_synced_at"`
}

// ListSubjectServiceGrants
//
//	SELECT service_grants.subject_sub,
//	       service_grants.service_id,
//	       service_grants.source_group,
//	       service_grants.granted_at,
//	       service_grants.last_synced_at
//	FROM service_grants
//	JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
//	WHERE service_grants.subject_sub = ?1
//	  AND service_catalog.enabled = 1
//	ORDER BY service_grants.service_id
func (q *Queries) ListSubjectServiceGrants(ctx context.Context, arg ListSubjectServiceGrantsParams) ([]ListSubjectServiceGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListSubjectServiceGrants, arg.SubjectSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectServiceGrantsRow{}
	for rows.Next() {
		var i ListSubjectServiceGrantsRow
		if err := rows.Scan(
			&i.SubjectSub,
			&i.ServiceID,
			&i.SourceGroup,
			&i.GrantedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTenantInstances = `-- name: ListTenantInstances :many
SELECT tenant_id,
       subject_sub,
       service_id,
       subject_key,
       tenant_instance_name,
       internal_dns_name,
       desired_state,
       runtime_state,
       coolify_resource_id,
       coolify_application_id,
       upstream_url,
       secret_version,
       last_healthy_at,
       last_reconciled_at,
       last_error,
       metadata,
       created_at,
       updated_at
FROM tenant_instances
ORDER BY service_id, subject_sub
`

// ListTenantInstances
//
//	SELECT tenant_id,
//	       subject_sub,
//	       service_id,
//	       subject_key,
//	       tenant_instance_name,
//	       internal_dns_name,
//	       desired_state,
//	       runtime_state,
//	       coolify_resource_id,
//	       coolify_application_id,
//	       upstream_url,
//	       secret_version,
//	       last_healthy_at,
//	       last_reconciled_at,
//	       last_error,
//	       metadata,
//	       created_at,
//	       updated_at
//	FROM tenant_instances
//	ORDER BY service_id, subject_sub
func (q *Queries) ListTenantInstances(ctx context.Context) ([]TenantInstance, error) {
	rows, err := q.db.QueryContext(ctx, ListTenantInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInstance{}
	for rows.Next() {
		var i TenantInstance
		if err := rows.Scan(
			&i.TenantID,
			&i.SubjectSub,
			&i.ServiceID,
			&i.SubjectKey,
			&i.TenantInstanceName,
			&i.InternalDnsName,
			&i.DesiredState,
			&i.RuntimeState,
			&i.CoolifyResourceID,
			&i.CoolifyApplicationID,
			&i.UpstreamUrl,
			&i.SecretVersion,
			&i.LastHealthyAt,
			&i.LastReconciledAt,
			&i.LastError,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkTenantDesiredDeleted = `-- name: MarkTenantDesiredDeleted :exec
UPDATE tenant_instances
SET desired_state = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?2
`

type MarkTenantDesiredDeletedParams struct {
	DesiredState string `db:"desired_state" json:"desired_state"`
	TenantID     []byte `db:"tenant_id" json:"tenant_id"`
}

// MarkTenantDesiredDeleted
//
//	UPDATE tenant_instances
//	SET desired_state = ?1,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?2
func (q *Queries) MarkTenantDesiredDeleted(ctx context.Context, arg MarkTenantDesiredDeletedParams) error {
	_, err := q.db.ExecContext(ctx, MarkTenantDesiredDeleted, arg.DesiredState, arg.TenantID)
	return err
}

const MarkTenantReconciled = `-- name: MarkTenantReconciled :exec
UPDATE tenant_instances
SET last_reconciled_at = ?1,
    last_error = NULLIF(?2, ''),
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?3
`

type MarkTenantReconciledParams struct {
	LastReconciledAt sql.NullString `db:"last_reconciled_at" json:"last_reconciled_at"`
	LastError        interface{}    `db:"last_error" json:"last_error"`
	TenantID         []byte         `db:"tenant_id" json:"tenant_id"`
}

// MarkTenantReconciled
//
//	UPDATE tenant_instances
//	SET last_reconciled_at = ?1,
//	    last_error = NULLIF(?2, ''),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?3
func (q *Queries) MarkTenantReconciled(ctx context.Context, arg MarkTenantReconciledParams) error {
	_, err := q.db.ExecContext(ctx, MarkTenantReconciled, arg.LastReconciledAt, arg.LastError, arg.TenantID)
	return err
}

const RebuildEffectiveServiceGrants = `-- name: RebuildEffectiveServiceGrants :exec
DELETE FROM service_grants
`

// RebuildEffectiveServiceGrants
//
//	DELETE FROM service_grants
func (q *Queries) RebuildEffectiveServiceGrants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, RebuildEffectiveServiceGrants)
	return err
}

const UpdateTenantRuntimeStatus = `-- name: UpdateTenantRuntimeStatus :exec
UPDATE tenant_instances
SET runtime_state = ?1,
    coolify_resource_id = CASE WHEN CAST(?2 AS boolean) THEN NULL WHEN ?3 = '' THEN coolify_resource_id ELSE ?3 END,
    coolify_application_id = CASE WHEN ?2 THEN NULL WHEN ?4 = '' THEN coolify_application_id ELSE ?4 END,
    upstream_url = CASE WHEN ?2 THEN NULL WHEN ?5 = '' THEN upstream_url ELSE ?5 END,
    last_healthy_at = CASE WHEN ?2 THEN NULL WHEN ?6 IS NULL THEN last_healthy_at ELSE ?6 END,
    last_error = NULLIF(?7, ''),
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?8
`

type UpdateTenantRuntimeStatusParams struct {
	RuntimeState           string      `db:"runtime_state" json:"runtime_state"`
	ClearRuntimeReferences bool        `db:"clear_runtime_references" json:"clear_runtime_references"`
	CoolifyResourceID      interface{} `db:"coolify_resource_id" json:"coolify_resource_id"`
	CoolifyApplicationID   interface{} `db:"coolify_application_id" json:"coolify_application_id"`
	UpstreamUrl            interface{} `db:"upstream_url" json:"upstream_url"`
	LastHealthyAt          interface{} `db:"last_healthy_at" json:"last_healthy_at"`
	LastError              interface{} `db:"last_error" json:"last_error"`
	TenantID               []byte      `db:"tenant_id" json:"tenant_id"`
}

// UpdateTenantRuntimeStatus
//
//	UPDATE tenant_instances
//	SET runtime_state = ?1,
//	    coolify_resource_id = CASE WHEN CAST(?2 AS boolean) THEN NULL WHEN ?3 = '' THEN coolify_resource_id ELSE ?3 END,
//	    coolify_application_id = CASE WHEN ?2 THEN NULL WHEN ?4 = '' THEN coolify_application_id ELSE ?4 END,
//	    upstream_url = CASE WHEN ?2 THEN NULL WHEN ?5 = '' THEN upstream_url ELSE ?5 END,
//	    last_healthy_at = CASE WHEN ?2 THEN NULL WHEN ?6 IS NULL THEN last_healthy_at ELSE ?6 END,
//	    last_error = NULLIF(?7, ''),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?8
func (q *Queries) UpdateTenantRuntimeStatus(ctx context.Context, arg UpdateTenantRuntimeStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTenantRuntimeStatus,
		arg.RuntimeState,
		arg.ClearRuntimeReferences,
		arg.CoolifyResourceID,
		arg.CoolifyApplicationID,
		arg.UpstreamUrl,
		arg.LastHealthyAt,
		arg.LastError,
		arg.TenantID,
	)
	return err
}

const UpsertManualServiceGrantSource = `-- name: UpsertManualServiceGrantSource :exec
INSERT INTO service_grant_sources (subject_sub, service_id, source_group, granted_at, last_synced_at)
VALUES (?1, ?2, 'manual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(subject_sub, service_id, source_group) DO UPDATE SET
    last_synced_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertManualServiceGrantSourceParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
	ServiceID  string `db:"service_id" json:"service_id"`
}

// UpsertManualServiceGrantSource
//
//	INSERT INTO service_grant_sources (subject_sub, service_id, source_group, granted_at, last_synced_at)
//	VALUES (?1, ?2, 'manual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
//	ON CONFLICT(subject_sub, service_id, source_group) DO UPDATE SET
//	    last_synced_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertManualServiceGrantSource(ctx context.Context, arg UpsertManualServiceGrantSourceParams) error {
	_, err := q.db.ExecContext(ctx, UpsertManualServiceGrantSource, arg.SubjectSub, arg.ServiceID)
	return err
}

const UpsertStaticTenantUpstream = `-- name: UpsertStaticTenantUpstream :exec
INSERT INTO tenant_instances (
    tenant_id,
    subject_sub,
    service_id,
    subject_key,
    tenant_instance_name,
    internal_dns_name,
    desired_state,
    runtime_state,
    upstream_url,
    last_healthy_at,
    last_error,
    metadata
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    'enabled',
    'ready',
    ?7,
    ?8,
    NULL,
    json_object('runtime_mode', 'static_upstream')
)
ON CONFLICT(subject_sub, service_id) DO UPDATE SET
    subject_key = excluded.subject_key,
    tenant_instance_name = excluded.tenant_instance_name,
    internal_dns_name = excluded.internal_dns_name,
    desired_state = 'enabled',
    runtime_state = 'ready',
    coolify_resource_id = NULL,
    coolify_application_id = NULL,
    upstream_url = excluded.upstream_url,
    last_healthy_at = excluded.last_healthy_at,
    last_error = NULL,
    metadata = json_patch(tenant_instances.metadata, excluded.metadata),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertStaticTenantUpstreamParams struct {
	TenantID           []byte         `db:"tenant_id" json:"tenant_id"`
	SubjectSub         string         `db:"subject_sub" json:"subject_sub"`
	ServiceID          string         `db:"service_id" json:"service_id"`
	SubjectKey         string         `db:"subject_key" json:"subject_key"`
	TenantInstanceName string         `db:"tenant_instance_name" json:"tenant_instance_name"`
	InternalDnsName    string         `db:"internal_dns_name" json:"internal_dns_name"`
	UpstreamUrl        sql.NullString `db:"upstream_url" json:"upstream_url"`
	LastHealthyAt      sql.NullString `db:"last_healthy_at" json:"last_healthy_at"`
}

// UpsertStaticTenantUpstream
//
//	INSERT INTO tenant_instances (
//	    tenant_id,
//	    subject_sub,
//	    service_id,
//	    subject_key,
//	    tenant_instance_name,
//	    internal_dns_name,
//	    desired_state,
//	    runtime_state,
//	    upstream_url,
//	    last_healthy_at,
//	    last_error,
//	    metadata
//	)
//	VALUES (
//	    ?1,
//	    ?2,
//	    ?3,
//	    ?4,
//	    ?5,
//	    ?6,
//	    'enabled',
//	    'ready',
//	    ?7,
//	    ?8,
//	    NULL,
//	    json_object('runtime_mode', 'static_upstream')
//	)
//	ON CONFLICT(subject_sub, service_id) DO UPDATE SET
//	    subject_key = excluded.subject_key,
//	    tenant_instance_name = excluded.tenant_instance_name,
//	    internal_dns_name = excluded.internal_dns_name,
//	    desired_state = 'enabled',
//	    runtime_state = 'ready',
//	    coolify_resource_id = NULL,
//	    coolify_application_id = NULL,
//	    upstream_url = excluded.upstream_url,
//	    last_healthy_at = excluded.last_healthy_at,
//	    last_error = NULL,
//	    metadata = json_patch(tenant_instances.metadata, excluded.metadata),
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertStaticTenantUpstream(ctx context.Context, arg UpsertStaticTenantUpstreamParams) error {
	_, err := q.db.ExecContext(ctx, UpsertStaticTenantUpstream,
		arg.TenantID,
		arg.SubjectSub,
		arg.ServiceID,
		arg.SubjectKey,
		arg.TenantInstanceName,
		arg.InternalDnsName,
		arg.UpstreamUrl,
		arg.LastHealthyAt,
	)
	return err
}

const UpsertSubject = `-- name: UpsertSubject :exec
INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(subject_sub) DO UPDATE SET
    subject_key = excluded.subject_key,
    preferred_username = excluded.preferred_username,
    email = excluded.email,
    display_name = excluded.display_name,
	account_binding_id = excluded.account_binding_id,
	account_binding_claim = excluded.account_binding_claim,
    last_synced_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSubjectParams struct {
	SubjectSub          string         `db:"subject_sub" json:"subject_sub"`
	SubjectKey          string         `db:"subject_key" json:"subject_key"`
	PreferredUsername   sql.NullString `db:"preferred_username" json:"preferred_username"`
	Email               sql.NullString `db:"email" json:"email"`
	DisplayName         sql.NullString `db:"display_name" json:"display_name"`
	AccountBindingID    sql.NullString `db:"account_binding_id" json:"account_binding_id"`
	AccountBindingClaim sql.NullString `db:"account_binding_claim" json:"account_binding_claim"`
}

// UpsertSubject
//
//	INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, updated_at)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
//	ON CONFLICT(subject_sub) DO UPDATE SET
//	    subject_key = excluded.subject_key,
//	    preferred_username = excluded.preferred_username,
//	    email = excluded.email,
//	    display_name = excluded.display_name,
//		account_binding_id = excluded.account_binding_id,
//		account_binding_claim = excluded.account_binding_claim,
//	    last_synced_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSubject,
		arg.SubjectSub,
		arg.SubjectKey,
		arg.PreferredUsername,
		arg.Email,
		arg.DisplayName,
		arg.AccountBindingID,
		arg.AccountBindingClaim,
	)
	return err
}

const UpsertSubjectPreservingMetadata = `-- name: UpsertSubjectPreservingMetadata :exec
INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(subject_sub) DO UPDATE SET
    subject_key = subjects.subject_key,
    preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
    email = COALESCE(excluded.email, subjects.email),
    display_name = COALESCE(excluded.display_name, subjects.display_name),
	account_binding_id = COALESCE(excluded.account_binding_id, subjects.account_binding_id),
	account_binding_claim = COALESCE(excluded.account_binding_claim, subjects.account_binding_claim),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSubjectPreservingMetadataParams struct {
	SubjectSub          string         `db:"subject_sub" json:"subject_sub"`
	SubjectKey          string         `db:"subject_key" json:"subject_key"`
	PreferredUsername   sql.NullString `db:"preferred_username" json:"preferred_username"`
	Email               sql.NullString `db:"email" json:"email"`
	DisplayName         sql.NullString `db:"display_name" json:"display_name"`
	AccountBindingID    sql.NullString `db:"account_binding_id" json:"account_binding_id"`
	AccountBindingClaim sql.NullString `db:"account_binding_claim" json:"account_binding_claim"`
}

// UpsertSubjectPreservingMetadata
//
//	INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, updated_at)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
//	ON CONFLICT(subject_sub) DO UPDATE SET
//	    subject_key = subjects.subject_key,
//	    preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
//	    email = COALESCE(excluded.email, subjects.email),
//	    display_name = COALESCE(excluded.display_name, subjects.display_name),
//		account_binding_id = COALESCE(excluded.account_binding_id, subjects.account_binding_id),
//		account_binding_claim = COALESCE(excluded.account_binding_claim, subjects.account_binding_claim),
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertSubjectPreservingMetadata(ctx context.Context, arg UpsertSubjectPreservingMetadataParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSubjectPreservingMetadata,
		arg.SubjectSub,
		arg.SubjectKey,
		arg.PreferredUsername,
		arg.Email,
		arg.DisplayName,
		arg.AccountBindingID,
		arg.AccountBindingClaim,
	)
	return err
}
