// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: controlplane.sql

package platformdb

import (
	"context"
	"database/sql"
	"strings"
)

const DeleteAllServiceGrants = `-- name: DeleteAllServiceGrants :exec
DELETE FROM service_grants
`

// DeleteAllServiceGrants
//
//	DELETE FROM service_grants
func (q *Queries) DeleteAllServiceGrants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllServiceGrants)
	return err
}

const DeleteStaleServiceGrants = `-- name: DeleteStaleServiceGrants :exec
DELETE FROM service_grants WHERE subject_sub NOT IN (/*SLICE:subject_subs*/?)
`

type DeleteStaleServiceGrantsParams struct {
	SubjectSubs []string `db:"subject_subs" json:"subject_subs"`
}

// DeleteStaleServiceGrants
//
//	DELETE FROM service_grants WHERE subject_sub NOT IN (/*SLICE:subject_subs*/?)
func (q *Queries) DeleteStaleServiceGrants(ctx context.Context, arg DeleteStaleServiceGrantsParams) error {
	query := DeleteStaleServiceGrants
	var queryParams []interface{}
	if len(arg.SubjectSubs) > 0 {
		for _, v := range arg.SubjectSubs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:subject_subs*/?", strings.Repeat(",?", len(arg.SubjectSubs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:subject_subs*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const DeleteSubjectGrants = `-- name: DeleteSubjectGrants :exec
DELETE FROM service_grants WHERE subject_sub = ?1
`

type DeleteSubjectGrantsParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
}

// DeleteSubjectGrants
//
//	DELETE FROM service_grants WHERE subject_sub = ?1
func (q *Queries) DeleteSubjectGrants(ctx context.Context, arg DeleteSubjectGrantsParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSubjectGrants, arg.SubjectSub)
	return err
}

const DeleteTenantInstance = `-- name: DeleteTenantInstance :exec
DELETE FROM tenant_instances WHERE tenant_id = ?1
`

type DeleteTenantInstanceParams struct {
	TenantID []byte `db:"tenant_id" json:"tenant_id"`
}

// DeleteTenantInstance
//
//	DELETE FROM tenant_instances WHERE tenant_id = ?1
func (q *Queries) DeleteTenantInstance(ctx context.Context, arg DeleteTenantInstanceParams) error {
	_, err := q.db.ExecContext(ctx, DeleteTenantInstance, arg.TenantID)
	return err
}

const EnableTenantInstance = `-- name: EnableTenantInstance :exec
UPDATE tenant_instances
SET subject_key = ?1,
    tenant_instance_name = ?2,
    internal_dns_name = ?3,
    desired_state = ?4,
    runtime_state = ?5,
    last_error = NULLIF(?6, ''),
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?7
`

type EnableTenantInstanceParams struct {
	SubjectKey         string      `db:"subject_key" json:"subject_key"`
	TenantInstanceName string      `db:"tenant_instance_name" json:"tenant_instance_name"`
	InternalDnsName    string      `db:"internal_dns_name" json:"internal_dns_name"`
	DesiredState       string      `db:"desired_state" json:"desired_state"`
	RuntimeState       string      `db:"runtime_state" json:"runtime_state"`
	LastError          interface{} `db:"last_error" json:"last_error"`
	TenantID           []byte      `db:"tenant_id" json:"tenant_id"`
}

// EnableTenantInstance
//
//	UPDATE tenant_instances
//	SET subject_key = ?1,
//	    tenant_instance_name = ?2,
//	    internal_dns_name = ?3,
//	    desired_state = ?4,
//	    runtime_state = ?5,
//	    last_error = NULLIF(?6, ''),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?7
func (q *Queries) EnableTenantInstance(ctx context.Context, arg EnableTenantInstanceParams) error {
	_, err := q.db.ExecContext(ctx, EnableTenantInstance,
		arg.SubjectKey,
		arg.TenantInstanceName,
		arg.InternalDnsName,
		arg.DesiredState,
		arg.RuntimeState,
		arg.LastError,
		arg.TenantID,
	)
	return err
}

const InsertReconcileRun = `-- name: InsertReconcileRun :exec
INSERT INTO reconcile_runs (run_id, tenant_id, desired_state, observed_state, action, status, details, started_at, finished_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertReconcileRunParams struct {
	RunID         []byte         `db:"run_id" json:"run_id"`
	TenantID      []byte         `db:"tenant_id" json:"tenant_id"`
	DesiredState  string         `db:"desired_state" json:"desired_state"`
	ObservedState sql.NullString `db:"observed_state" json:"observed_state"`
	Action        string         `db:"action" json:"action"`
	Status        string         `db:"status" json:"status"`
	Details       string         `db:"details" json:"details"`
	StartedAt     string         `db:"started_at" json:"started_at"`
	FinishedAt    sql.NullString `db:"finished_at" json:"finished_at"`
}

// InsertReconcileRun
//
//	INSERT INTO reconcile_runs (run_id, tenant_id, desired_state, observed_state, action, status, details, started_at, finished_at)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
func (q *Queries) InsertReconcileRun(ctx context.Context, arg InsertReconcileRunParams) error {
	_, err := q.db.ExecContext(ctx, InsertReconcileRun,
		arg.RunID,
		arg.TenantID,
		arg.DesiredState,
		arg.ObservedState,
		arg.Action,
		arg.Status,
		arg.Details,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const InsertServiceGrant = `-- name: InsertServiceGrant :exec
INSERT INTO service_grants (subject_sub, service_id, source_group, granted_at, last_synced_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertServiceGrantParams struct {
	SubjectSub   string `db:"subject_sub" json:"subject_sub"`
	ServiceID    string `db:"service_id" json:"service_id"`
	SourceGroup  string `db:"source_group" json:"source_group"`
	GrantedAt    string `db:"granted_at" json:"granted_at"`
	LastSyncedAt string `db:"last_synced_at" json:"last_synced_at"`
}

// InsertServiceGrant
//
//	INSERT INTO service_grants (subject_sub, service_id, source_group, granted_at, last_synced_at)
//	VALUES (?1, ?2, ?3, ?4, ?5)
func (q *Queries) InsertServiceGrant(ctx context.Context, arg InsertServiceGrantParams) error {
	_, err := q.db.ExecContext(ctx, InsertServiceGrant,
		arg.SubjectSub,
		arg.ServiceID,
		arg.SourceGroup,
		arg.GrantedAt,
		arg.LastSyncedAt,
	)
	return err
}

const InsertTenantInstance = `-- name: InsertTenantInstance :exec
INSERT INTO tenant_instances (tenant_id, subject_sub, service_id, subject_key, tenant_instance_name, internal_dns_name, desired_state, runtime_state)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertTenantInstanceParams struct {
	TenantID           []byte `db:"tenant_id" json:"tenant_id"`
	SubjectSub         string `db:"subject_sub" json:"subject_sub"`
	ServiceID          string `db:"service_id" json:"service_id"`
	SubjectKey         string `db:"subject_key" json:"subject_key"`
	TenantInstanceName string `db:"tenant_instance_name" json:"tenant_instance_name"`
	InternalDnsName    string `db:"internal_dns_name" json:"internal_dns_name"`
	DesiredState       string `db:"desired_state" json:"desired_state"`
	RuntimeState       string `db:"runtime_state" json:"runtime_state"`
}

// InsertTenantInstance
//
//	INSERT INTO tenant_instances (tenant_id, subject_sub, service_id, subject_key, tenant_instance_name, internal_dns_name, desired_state, runtime_state)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
func (q *Queries) InsertTenantInstance(ctx context.Context, arg InsertTenantInstanceParams) error {
	_, err := q.db.ExecContext(ctx, InsertTenantInstance,
		arg.TenantID,
		arg.SubjectSub,
		arg.ServiceID,
		arg.SubjectKey,
		arg.TenantInstanceName,
		arg.InternalDnsName,
		arg.DesiredState,
		arg.RuntimeState,
	)
	return err
}

const ListDesiredTenantSpecs = `-- name: ListDesiredTenantSpecs :many
SELECT subjects.subject_sub,
       subjects.subject_key,
       COALESCE(subjects.preferred_username, '') AS preferred_username,
       COALESCE(subjects.email, '') AS email,
       COALESCE(subjects.display_name, '') AS display_name,
       service_grants.service_id
FROM service_grants
JOIN subjects ON subjects.subject_sub = service_grants.subject_sub
JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
WHERE service_catalog.enabled = 1
ORDER BY service_grants.service_id, subjects.subject_sub
`

type ListDesiredTenantSpecsRow struct {
	SubjectSub        string `db:"subject_sub" json:"subject_sub"`
	SubjectKey        string `db:"subject_key" json:"subject_key"`
	PreferredUsername string `db:"preferred_username" json:"preferred_username"`
	Email             string `db:"email" json:"email"`
	DisplayName       string `db:"display_name" json:"display_name"`
	ServiceID         string `db:"service_id" json:"service_id"`
}

// ListDesiredTenantSpecs
//
//	SELECT subjects.subject_sub,
//	       subjects.subject_key,
//	       COALESCE(subjects.preferred_username, '') AS preferred_username,
//	       COALESCE(subjects.email, '') AS email,
//	       COALESCE(subjects.display_name, '') AS display_name,
//	       service_grants.service_id
//	FROM service_grants
//	JOIN subjects ON subjects.subject_sub = service_grants.subject_sub
//	JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
//	WHERE service_catalog.enabled = 1
//	ORDER BY service_grants.service_id, subjects.subject_sub
func (q *Queries) ListDesiredTenantSpecs(ctx context.Context) ([]ListDesiredTenantSpecsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDesiredTenantSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDesiredTenantSpecsRow{}
	for rows.Next() {
		var i ListDesiredTenantSpecsRow
		if err := rows.Scan(
			&i.SubjectSub,
			&i.SubjectKey,
			&i.PreferredUsername,
			&i.Email,
			&i.DisplayName,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTenantInstances = `-- name: ListTenantInstances :many
SELECT tenant_id,
       subject_sub,
       service_id,
       subject_key,
       tenant_instance_name,
       internal_dns_name,
       desired_state,
       runtime_state,
       coolify_resource_id,
       coolify_application_id,
       upstream_url,
       secret_version,
       last_healthy_at,
       last_reconciled_at,
       last_error,
       metadata,
       created_at,
       updated_at
FROM tenant_instances
ORDER BY service_id, subject_sub
`

// ListTenantInstances
//
//	SELECT tenant_id,
//	       subject_sub,
//	       service_id,
//	       subject_key,
//	       tenant_instance_name,
//	       internal_dns_name,
//	       desired_state,
//	       runtime_state,
//	       coolify_resource_id,
//	       coolify_application_id,
//	       upstream_url,
//	       secret_version,
//	       last_healthy_at,
//	       last_reconciled_at,
//	       last_error,
//	       metadata,
//	       created_at,
//	       updated_at
//	FROM tenant_instances
//	ORDER BY service_id, subject_sub
func (q *Queries) ListTenantInstances(ctx context.Context) ([]TenantInstance, error) {
	rows, err := q.db.QueryContext(ctx, ListTenantInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInstance{}
	for rows.Next() {
		var i TenantInstance
		if err := rows.Scan(
			&i.TenantID,
			&i.SubjectSub,
			&i.ServiceID,
			&i.SubjectKey,
			&i.TenantInstanceName,
			&i.InternalDnsName,
			&i.DesiredState,
			&i.RuntimeState,
			&i.CoolifyResourceID,
			&i.CoolifyApplicationID,
			&i.UpstreamUrl,
			&i.SecretVersion,
			&i.LastHealthyAt,
			&i.LastReconciledAt,
			&i.LastError,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkTenantDesiredDeleted = `-- name: MarkTenantDesiredDeleted :exec
UPDATE tenant_instances
SET desired_state = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?2
`

type MarkTenantDesiredDeletedParams struct {
	DesiredState string `db:"desired_state" json:"desired_state"`
	TenantID     []byte `db:"tenant_id" json:"tenant_id"`
}

// MarkTenantDesiredDeleted
//
//	UPDATE tenant_instances
//	SET desired_state = ?1,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?2
func (q *Queries) MarkTenantDesiredDeleted(ctx context.Context, arg MarkTenantDesiredDeletedParams) error {
	_, err := q.db.ExecContext(ctx, MarkTenantDesiredDeleted, arg.DesiredState, arg.TenantID)
	return err
}

const MarkTenantReconciled = `-- name: MarkTenantReconciled :exec
UPDATE tenant_instances
SET last_reconciled_at = ?1,
    last_error = NULLIF(?2, ''),
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?3
`

type MarkTenantReconciledParams struct {
	LastReconciledAt sql.NullString `db:"last_reconciled_at" json:"last_reconciled_at"`
	LastError        interface{}    `db:"last_error" json:"last_error"`
	TenantID         []byte         `db:"tenant_id" json:"tenant_id"`
}

// MarkTenantReconciled
//
//	UPDATE tenant_instances
//	SET last_reconciled_at = ?1,
//	    last_error = NULLIF(?2, ''),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?3
func (q *Queries) MarkTenantReconciled(ctx context.Context, arg MarkTenantReconciledParams) error {
	_, err := q.db.ExecContext(ctx, MarkTenantReconciled, arg.LastReconciledAt, arg.LastError, arg.TenantID)
	return err
}

const UpdateTenantRuntimeStatus = `-- name: UpdateTenantRuntimeStatus :exec
UPDATE tenant_instances
SET runtime_state = ?1,
    coolify_resource_id = CASE WHEN ?2 THEN NULL WHEN ?3 = '' THEN coolify_resource_id ELSE ?3 END,
    coolify_application_id = CASE WHEN ?2 THEN NULL WHEN ?4 = '' THEN coolify_application_id ELSE ?4 END,
    upstream_url = CASE WHEN ?2 THEN NULL WHEN ?5 = '' THEN upstream_url ELSE ?5 END,
    last_healthy_at = CASE WHEN ?2 THEN NULL WHEN ?6 IS NULL THEN last_healthy_at ELSE ?6 END,
    last_error = NULLIF(?7, ''),
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = ?8
`

type UpdateTenantRuntimeStatusParams struct {
	RuntimeState           string         `db:"runtime_state" json:"runtime_state"`
	ClearRuntimeReferences sql.NullString `db:"clear_runtime_references" json:"clear_runtime_references"`
	CoolifyResourceID      interface{}    `db:"coolify_resource_id" json:"coolify_resource_id"`
	CoolifyApplicationID   interface{}    `db:"coolify_application_id" json:"coolify_application_id"`
	UpstreamUrl            interface{}    `db:"upstream_url" json:"upstream_url"`
	LastHealthyAt          interface{}    `db:"last_healthy_at" json:"last_healthy_at"`
	LastError              interface{}    `db:"last_error" json:"last_error"`
	TenantID               []byte         `db:"tenant_id" json:"tenant_id"`
}

// UpdateTenantRuntimeStatus
//
//	UPDATE tenant_instances
//	SET runtime_state = ?1,
//	    coolify_resource_id = CASE WHEN ?2 THEN NULL WHEN ?3 = '' THEN coolify_resource_id ELSE ?3 END,
//	    coolify_application_id = CASE WHEN ?2 THEN NULL WHEN ?4 = '' THEN coolify_application_id ELSE ?4 END,
//	    upstream_url = CASE WHEN ?2 THEN NULL WHEN ?5 = '' THEN upstream_url ELSE ?5 END,
//	    last_healthy_at = CASE WHEN ?2 THEN NULL WHEN ?6 IS NULL THEN last_healthy_at ELSE ?6 END,
//	    last_error = NULLIF(?7, ''),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE tenant_id = ?8
func (q *Queries) UpdateTenantRuntimeStatus(ctx context.Context, arg UpdateTenantRuntimeStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTenantRuntimeStatus,
		arg.RuntimeState,
		arg.ClearRuntimeReferences,
		arg.CoolifyResourceID,
		arg.CoolifyApplicationID,
		arg.UpstreamUrl,
		arg.LastHealthyAt,
		arg.LastError,
		arg.TenantID,
	)
	return err
}

const UpsertSubject = `-- name: UpsertSubject :exec
INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, last_synced_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(subject_sub) DO UPDATE SET
    subject_key = excluded.subject_key,
    preferred_username = excluded.preferred_username,
    email = excluded.email,
    display_name = excluded.display_name,
    last_synced_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSubjectParams struct {
	SubjectSub        string         `db:"subject_sub" json:"subject_sub"`
	SubjectKey        string         `db:"subject_key" json:"subject_key"`
	PreferredUsername sql.NullString `db:"preferred_username" json:"preferred_username"`
	Email             sql.NullString `db:"email" json:"email"`
	DisplayName       sql.NullString `db:"display_name" json:"display_name"`
}

// UpsertSubject
//
//	INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, last_synced_at, updated_at)
//	VALUES (?1, ?2, ?3, ?4, ?5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
//	ON CONFLICT(subject_sub) DO UPDATE SET
//	    subject_key = excluded.subject_key,
//	    preferred_username = excluded.preferred_username,
//	    email = excluded.email,
//	    display_name = excluded.display_name,
//	    last_synced_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSubject,
		arg.SubjectSub,
		arg.SubjectKey,
		arg.PreferredUsername,
		arg.Email,
		arg.DisplayName,
	)
	return err
}
