// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edge.sql

package platformdb

import (
	"context"
	"database/sql"
	"strings"
)

const AllowedServiceGrant = `-- name: AllowedServiceGrant :one
SELECT EXISTS (
    SELECT 1
    FROM service_grants
    JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
    WHERE service_grants.subject_sub = ?1
      AND service_grants.service_id = ?2
      AND service_catalog.enabled = 1
) AS allowed
`

type AllowedServiceGrantParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
	ServiceID  string `db:"service_id" json:"service_id"`
}

// AllowedServiceGrant
//
//	SELECT EXISTS (
//	    SELECT 1
//	    FROM service_grants
//	    JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
//	    WHERE service_grants.subject_sub = ?1
//	      AND service_grants.service_id = ?2
//	      AND service_catalog.enabled = 1
//	) AS allowed
func (q *Queries) AllowedServiceGrant(ctx context.Context, arg AllowedServiceGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, AllowedServiceGrant, arg.SubjectSub, arg.ServiceID)
	var allowed int64
	err := row.Scan(&allowed)
	return allowed, err
}

const ApproveDeviceAuthorization = `-- name: ApproveDeviceAuthorization :execrows
UPDATE oauth_device_authorizations
SET subject_sub = ?1,
    status = 'approved',
    approved_at = ?2,
    updated_at = ?2
WHERE device_authorization_id = ?3
  AND status = 'pending'
  AND expires_at > ?4
`

type ApproveDeviceAuthorizationParams struct {
	SubjectSub            sql.NullString `db:"subject_sub" json:"subject_sub"`
	ApprovedAt            sql.NullString `db:"approved_at" json:"approved_at"`
	DeviceAuthorizationID []byte         `db:"device_authorization_id" json:"device_authorization_id"`
	Now                   string         `db:"now" json:"now"`
}

// ApproveDeviceAuthorization
//
//	UPDATE oauth_device_authorizations
//	SET subject_sub = ?1,
//	    status = 'approved',
//	    approved_at = ?2,
//	    updated_at = ?2
//	WHERE device_authorization_id = ?3
//	  AND status = 'pending'
//	  AND expires_at > ?4
func (q *Queries) ApproveDeviceAuthorization(ctx context.Context, arg ApproveDeviceAuthorizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ApproveDeviceAuthorization,
		arg.SubjectSub,
		arg.ApprovedAt,
		arg.DeviceAuthorizationID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ConsumeDeviceAuthorization = `-- name: ConsumeDeviceAuthorization :execrows
UPDATE oauth_device_authorizations
SET status = 'consumed',
    consumed_at = ?1,
    updated_at = ?1
WHERE device_authorization_id = ?2
  AND status = 'approved'
  AND subject_sub IS NOT NULL
  AND expires_at > ?3
`

type ConsumeDeviceAuthorizationParams struct {
	ConsumedAt            sql.NullString `db:"consumed_at" json:"consumed_at"`
	DeviceAuthorizationID []byte         `db:"device_authorization_id" json:"device_authorization_id"`
	Now                   string         `db:"now" json:"now"`
}

// ConsumeDeviceAuthorization
//
//	UPDATE oauth_device_authorizations
//	SET status = 'consumed',
//	    consumed_at = ?1,
//	    updated_at = ?1
//	WHERE device_authorization_id = ?2
//	  AND status = 'approved'
//	  AND subject_sub IS NOT NULL
//	  AND expires_at > ?3
func (q *Queries) ConsumeDeviceAuthorization(ctx context.Context, arg ConsumeDeviceAuthorizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ConsumeDeviceAuthorization, arg.ConsumedAt, arg.DeviceAuthorizationID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ConsumeOAuthSessionByCodeHash = `-- name: ConsumeOAuthSessionByCodeHash :one
UPDATE oauth_sessions
SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
RETURNING session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
`

type ConsumeOAuthSessionByCodeHashParams struct {
	AuthorizationCodeHash sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
}

type ConsumeOAuthSessionByCodeHashRow struct {
	SessionID                   []byte         `db:"session_id" json:"session_id"`
	SubjectSub                  sql.NullString `db:"subject_sub" json:"subject_sub"`
	ClientID                    string         `db:"client_id" json:"client_id"`
	ServiceID                   sql.NullString `db:"service_id" json:"service_id"`
	Resource                    string         `db:"resource" json:"resource"`
	RedirectUri                 string         `db:"redirect_uri" json:"redirect_uri"`
	Scope                       string         `db:"scope" json:"scope"`
	CodeChallenge               sql.NullString `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod         sql.NullString `db:"code_challenge_method" json:"code_challenge_method"`
	AuthorizationCodeHash       sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
	AuthorizationCodeCiphertext []byte         `db:"authorization_code_ciphertext" json:"authorization_code_ciphertext"`
	AccessTokenHash             sql.NullString `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenCiphertext       []byte         `db:"access_token_ciphertext" json:"access_token_ciphertext"`
	RefreshTokenHash            sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenCiphertext      []byte         `db:"refresh_token_ciphertext" json:"refresh_token_ciphertext"`
	CodeCreateAt                sql.NullString `db:"code_create_at" json:"code_create_at"`
	CodeExpiresInSeconds        int64          `db:"code_expires_in_seconds" json:"code_expires_in_seconds"`
	AccessCreateAt              sql.NullString `db:"access_create_at" json:"access_create_at"`
	AccessExpiresInSeconds      int64          `db:"access_expires_in_seconds" json:"access_expires_in_seconds"`
	RefreshCreateAt             sql.NullString `db:"refresh_create_at" json:"refresh_create_at"`
	RefreshExpiresInSeconds     int64          `db:"refresh_expires_in_seconds" json:"refresh_expires_in_seconds"`
	ExpiresAt                   sql.NullString `db:"expires_at" json:"expires_at"`
	IssuedVia                   string         `db:"issued_via" json:"issued_via"`
	OperatorReason              sql.NullString `db:"operator_reason" json:"operator_reason"`
}

// ConsumeOAuthSessionByCodeHash
//
//	UPDATE oauth_sessions
//	SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
//	WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
//	RETURNING session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
func (q *Queries) ConsumeOAuthSessionByCodeHash(ctx context.Context, arg ConsumeOAuthSessionByCodeHashParams) (ConsumeOAuthSessionByCodeHashRow, error) {
	row := q.db.QueryRowContext(ctx, ConsumeOAuthSessionByCodeHash, arg.AuthorizationCodeHash)
	var i ConsumeOAuthSessionByCodeHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SubjectSub,
		&i.ClientID,
		&i.ServiceID,
		&i.Resource,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthorizationCodeHash,
		&i.AuthorizationCodeCiphertext,
		&i.AccessTokenHash,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenHash,
		&i.RefreshTokenCiphertext,
		&i.CodeCreateAt,
		&i.CodeExpiresInSeconds,
		&i.AccessCreateAt,
		&i.AccessExpiresInSeconds,
		&i.RefreshCreateAt,
		&i.RefreshExpiresInSeconds,
		&i.ExpiresAt,
		&i.IssuedVia,
		&i.OperatorReason,
	)
	return i, err
}

const ConsumeOAuthSessionByRefreshHash = `-- name: ConsumeOAuthSessionByRefreshHash :one
UPDATE oauth_sessions
SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE refresh_token_hash = ?1 AND consumed_at IS NULL
RETURNING session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
`

type ConsumeOAuthSessionByRefreshHashParams struct {
	RefreshTokenHash sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
}

type ConsumeOAuthSessionByRefreshHashRow struct {
	SessionID                   []byte         `db:"session_id" json:"session_id"`
	SubjectSub                  sql.NullString `db:"subject_sub" json:"subject_sub"`
	ClientID                    string         `db:"client_id" json:"client_id"`
	ServiceID                   sql.NullString `db:"service_id" json:"service_id"`
	Resource                    string         `db:"resource" json:"resource"`
	RedirectUri                 string         `db:"redirect_uri" json:"redirect_uri"`
	Scope                       string         `db:"scope" json:"scope"`
	CodeChallenge               sql.NullString `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod         sql.NullString `db:"code_challenge_method" json:"code_challenge_method"`
	AuthorizationCodeHash       sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
	AuthorizationCodeCiphertext []byte         `db:"authorization_code_ciphertext" json:"authorization_code_ciphertext"`
	AccessTokenHash             sql.NullString `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenCiphertext       []byte         `db:"access_token_ciphertext" json:"access_token_ciphertext"`
	RefreshTokenHash            sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenCiphertext      []byte         `db:"refresh_token_ciphertext" json:"refresh_token_ciphertext"`
	CodeCreateAt                sql.NullString `db:"code_create_at" json:"code_create_at"`
	CodeExpiresInSeconds        int64          `db:"code_expires_in_seconds" json:"code_expires_in_seconds"`
	AccessCreateAt              sql.NullString `db:"access_create_at" json:"access_create_at"`
	AccessExpiresInSeconds      int64          `db:"access_expires_in_seconds" json:"access_expires_in_seconds"`
	RefreshCreateAt             sql.NullString `db:"refresh_create_at" json:"refresh_create_at"`
	RefreshExpiresInSeconds     int64          `db:"refresh_expires_in_seconds" json:"refresh_expires_in_seconds"`
	ExpiresAt                   sql.NullString `db:"expires_at" json:"expires_at"`
	IssuedVia                   string         `db:"issued_via" json:"issued_via"`
	OperatorReason              sql.NullString `db:"operator_reason" json:"operator_reason"`
}

// ConsumeOAuthSessionByRefreshHash
//
//	UPDATE oauth_sessions
//	SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
//	WHERE refresh_token_hash = ?1 AND consumed_at IS NULL
//	RETURNING session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
func (q *Queries) ConsumeOAuthSessionByRefreshHash(ctx context.Context, arg ConsumeOAuthSessionByRefreshHashParams) (ConsumeOAuthSessionByRefreshHashRow, error) {
	row := q.db.QueryRowContext(ctx, ConsumeOAuthSessionByRefreshHash, arg.RefreshTokenHash)
	var i ConsumeOAuthSessionByRefreshHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SubjectSub,
		&i.ClientID,
		&i.ServiceID,
		&i.Resource,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthorizationCodeHash,
		&i.AuthorizationCodeCiphertext,
		&i.AccessTokenHash,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenHash,
		&i.RefreshTokenCiphertext,
		&i.CodeCreateAt,
		&i.CodeExpiresInSeconds,
		&i.AccessCreateAt,
		&i.AccessExpiresInSeconds,
		&i.RefreshCreateAt,
		&i.RefreshExpiresInSeconds,
		&i.ExpiresAt,
		&i.IssuedVia,
		&i.OperatorReason,
	)
	return i, err
}

const CountAllowedServiceGrants = `-- name: CountAllowedServiceGrants :one
SELECT COUNT(DISTINCT service_grants.service_id) AS allowed_count
FROM service_grants
JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
WHERE service_grants.subject_sub = ?1
  AND service_catalog.enabled = 1
  AND service_grants.service_id IN (/*SLICE:service_ids*/?)
`

type CountAllowedServiceGrantsParams struct {
	SubjectSub string   `db:"subject_sub" json:"subject_sub"`
	ServiceIds []string `db:"service_ids" json:"service_ids"`
}

// CountAllowedServiceGrants
//
//	SELECT COUNT(DISTINCT service_grants.service_id) AS allowed_count
//	FROM service_grants
//	JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
//	WHERE service_grants.subject_sub = ?1
//	  AND service_catalog.enabled = 1
//	  AND service_grants.service_id IN (/*SLICE:service_ids*/?)
func (q *Queries) CountAllowedServiceGrants(ctx context.Context, arg CountAllowedServiceGrantsParams) (int64, error) {
	query := CountAllowedServiceGrants
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SubjectSub)
	if len(arg.ServiceIds) > 0 {
		for _, v := range arg.ServiceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:service_ids*/?", strings.Repeat(",?", len(arg.ServiceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:service_ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var allowed_count int64
	err := row.Scan(&allowed_count)
	return allowed_count, err
}

const CountAuditEventsByType = `-- name: CountAuditEventsByType :one
SELECT COUNT(*) AS audit_count
FROM audit_events
WHERE event_type = ?1
`

type CountAuditEventsByTypeParams struct {
	EventType string `db:"event_type" json:"event_type"`
}

// CountAuditEventsByType
//
//	SELECT COUNT(*) AS audit_count
//	FROM audit_events
//	WHERE event_type = ?1
func (q *Queries) CountAuditEventsByType(ctx context.Context, arg CountAuditEventsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAuditEventsByType, arg.EventType)
	var audit_count int64
	err := row.Scan(&audit_count)
	return audit_count, err
}

const CreateDeviceAuthorization = `-- name: CreateDeviceAuthorization :exec
INSERT INTO oauth_device_authorizations (
    device_authorization_id,
    client_id,
    service_id,
    resource,
    scope,
    device_code_hash,
    user_code_hash,
    user_code_display,
    status,
    interval_seconds,
    expires_at,
    created_at,
    updated_at
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    'pending',
    ?9,
    ?10,
    ?11,
    ?11
)
`

type CreateDeviceAuthorizationParams struct {
	DeviceAuthorizationID []byte `db:"device_authorization_id" json:"device_authorization_id"`
	ClientID              string `db:"client_id" json:"client_id"`
	ServiceID             string `db:"service_id" json:"service_id"`
	Resource              string `db:"resource" json:"resource"`
	Scope                 string `db:"scope" json:"scope"`
	DeviceCodeHash        string `db:"device_code_hash" json:"device_code_hash"`
	UserCodeHash          string `db:"user_code_hash" json:"user_code_hash"`
	UserCodeDisplay       string `db:"user_code_display" json:"user_code_display"`
	IntervalSeconds       int64  `db:"interval_seconds" json:"interval_seconds"`
	ExpiresAt             string `db:"expires_at" json:"expires_at"`
	CreatedAt             string `db:"created_at" json:"created_at"`
}

// CreateDeviceAuthorization
//
//	INSERT INTO oauth_device_authorizations (
//	    device_authorization_id,
//	    client_id,
//	    service_id,
//	    resource,
//	    scope,
//	    device_code_hash,
//	    user_code_hash,
//	    user_code_display,
//	    status,
//	    interval_seconds,
//	    expires_at,
//	    created_at,
//	    updated_at
//	)
//	VALUES (
//	    ?1,
//	    ?2,
//	    ?3,
//	    ?4,
//	    ?5,
//	    ?6,
//	    ?7,
//	    ?8,
//	    'pending',
//	    ?9,
//	    ?10,
//	    ?11,
//	    ?11
//	)
func (q *Queries) CreateDeviceAuthorization(ctx context.Context, arg CreateDeviceAuthorizationParams) error {
	_, err := q.db.ExecContext(ctx, CreateDeviceAuthorization,
		arg.DeviceAuthorizationID,
		arg.ClientID,
		arg.ServiceID,
		arg.Resource,
		arg.Scope,
		arg.DeviceCodeHash,
		arg.UserCodeHash,
		arg.UserCodeDisplay,
		arg.IntervalSeconds,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const CreateOAuthClient = `-- name: CreateOAuthClient :exec
INSERT INTO oauth_clients (client_id, client_name, created_by_subject_sub, redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, client_secret_hash, metadata, created_at, updated_at)
VALUES (?1, ?2, NULLIF(?3, ''), ?4, ?5, ?6, ?7, ?8, ?9, '{}', ?10, ?10)
`

type CreateOAuthClientParams struct {
	ClientID                string         `db:"client_id" json:"client_id"`
	ClientName              string         `db:"client_name" json:"client_name"`
	CreatedBySubjectSub     interface{}    `db:"created_by_subject_sub" json:"created_by_subject_sub"`
	RedirectUris            string         `db:"redirect_uris" json:"redirect_uris"`
	GrantTypes              string         `db:"grant_types" json:"grant_types"`
	ResponseTypes           string         `db:"response_types" json:"response_types"`
	Scopes                  string         `db:"scopes" json:"scopes"`
	TokenEndpointAuthMethod string         `db:"token_endpoint_auth_method" json:"token_endpoint_auth_method"`
	ClientSecretHash        sql.NullString `db:"client_secret_hash" json:"client_secret_hash"`
	CreatedAt               string         `db:"created_at" json:"created_at"`
}

// CreateOAuthClient
//
//	INSERT INTO oauth_clients (client_id, client_name, created_by_subject_sub, redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, client_secret_hash, metadata, created_at, updated_at)
//	VALUES (?1, ?2, NULLIF(?3, ''), ?4, ?5, ?6, ?7, ?8, ?9, '{}', ?10, ?10)
func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, CreateOAuthClient,
		arg.ClientID,
		arg.ClientName,
		arg.CreatedBySubjectSub,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Scopes,
		arg.TokenEndpointAuthMethod,
		arg.ClientSecretHash,
		arg.CreatedAt,
	)
	return err
}

const DeleteBrowserSession = `-- name: DeleteBrowserSession :exec
DELETE FROM edge_browser_sessions WHERE session_id = ?1
`

type DeleteBrowserSessionParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

// DeleteBrowserSession
//
//	DELETE FROM edge_browser_sessions WHERE session_id = ?1
func (q *Queries) DeleteBrowserSession(ctx context.Context, arg DeleteBrowserSessionParams) error {
	_, err := q.db.ExecContext(ctx, DeleteBrowserSession, arg.SessionID)
	return err
}

const DeleteOAuthSessionByAccessHash = `-- name: DeleteOAuthSessionByAccessHash :exec
DELETE FROM oauth_sessions WHERE access_token_hash = ?1
`

type DeleteOAuthSessionByAccessHashParams struct {
	AccessTokenHash sql.NullString `db:"access_token_hash" json:"access_token_hash"`
}

// DeleteOAuthSessionByAccessHash
//
//	DELETE FROM oauth_sessions WHERE access_token_hash = ?1
func (q *Queries) DeleteOAuthSessionByAccessHash(ctx context.Context, arg DeleteOAuthSessionByAccessHashParams) error {
	_, err := q.db.ExecContext(ctx, DeleteOAuthSessionByAccessHash, arg.AccessTokenHash)
	return err
}

const DeleteOAuthSessionByCodeHash = `-- name: DeleteOAuthSessionByCodeHash :exec
DELETE FROM oauth_sessions WHERE authorization_code_hash = ?1
`

type DeleteOAuthSessionByCodeHashParams struct {
	AuthorizationCodeHash sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
}

// DeleteOAuthSessionByCodeHash
//
//	DELETE FROM oauth_sessions WHERE authorization_code_hash = ?1
func (q *Queries) DeleteOAuthSessionByCodeHash(ctx context.Context, arg DeleteOAuthSessionByCodeHashParams) error {
	_, err := q.db.ExecContext(ctx, DeleteOAuthSessionByCodeHash, arg.AuthorizationCodeHash)
	return err
}

const DeleteOAuthSessionByRefreshHash = `-- name: DeleteOAuthSessionByRefreshHash :exec
DELETE FROM oauth_sessions WHERE refresh_token_hash = ?1
`

type DeleteOAuthSessionByRefreshHashParams struct {
	RefreshTokenHash sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
}

// DeleteOAuthSessionByRefreshHash
//
//	DELETE FROM oauth_sessions WHERE refresh_token_hash = ?1
func (q *Queries) DeleteOAuthSessionByRefreshHash(ctx context.Context, arg DeleteOAuthSessionByRefreshHashParams) error {
	_, err := q.db.ExecContext(ctx, DeleteOAuthSessionByRefreshHash, arg.RefreshTokenHash)
	return err
}

const DeleteOperatorOAuthSessionByID = `-- name: DeleteOperatorOAuthSessionByID :execrows
DELETE FROM oauth_sessions
WHERE session_id = ?1
  AND issued_via = 'operator'
  AND client_id = ?2
`

type DeleteOperatorOAuthSessionByIDParams struct {
	SessionID []byte `db:"session_id" json:"session_id"`
	ClientID  string `db:"client_id" json:"client_id"`
}

// DeleteOperatorOAuthSessionByID
//
//	DELETE FROM oauth_sessions
//	WHERE session_id = ?1
//	  AND issued_via = 'operator'
//	  AND client_id = ?2
func (q *Queries) DeleteOperatorOAuthSessionByID(ctx context.Context, arg DeleteOperatorOAuthSessionByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteOperatorOAuthSessionByID, arg.SessionID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeletePendingLogin = `-- name: DeletePendingLogin :exec
DELETE FROM edge_pending_logins WHERE state = ?1
`

type DeletePendingLoginParams struct {
	State string `db:"state" json:"state"`
}

// DeletePendingLogin
//
//	DELETE FROM edge_pending_logins WHERE state = ?1
func (q *Queries) DeletePendingLogin(ctx context.Context, arg DeletePendingLoginParams) error {
	_, err := q.db.ExecContext(ctx, DeletePendingLogin, arg.State)
	return err
}

const DenyDeviceAuthorization = `-- name: DenyDeviceAuthorization :execrows
UPDATE oauth_device_authorizations
SET status = 'denied',
    denied_at = ?1,
    updated_at = ?1
WHERE device_authorization_id = ?2
  AND status = 'pending'
  AND expires_at > ?3
`

type DenyDeviceAuthorizationParams struct {
	DeniedAt              sql.NullString `db:"denied_at" json:"denied_at"`
	DeviceAuthorizationID []byte         `db:"device_authorization_id" json:"device_authorization_id"`
	Now                   string         `db:"now" json:"now"`
}

// DenyDeviceAuthorization
//
//	UPDATE oauth_device_authorizations
//	SET status = 'denied',
//	    denied_at = ?1,
//	    updated_at = ?1
//	WHERE device_authorization_id = ?2
//	  AND status = 'pending'
//	  AND expires_at > ?3
func (q *Queries) DenyDeviceAuthorization(ctx context.Context, arg DenyDeviceAuthorizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DenyDeviceAuthorization, arg.DeniedAt, arg.DeviceAuthorizationID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const EdgeUpsertSubject = `-- name: EdgeUpsertSubject :exec
INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, created_at, updated_at)
VALUES (?1, ?2, NULLIF(?3, ''), NULLIF(?4, ''), NULLIF(?5, ''), NULLIF(?6, ''), NULLIF(?7, ''), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(subject_sub) DO UPDATE SET
    subject_key = excluded.subject_key,
    preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
    email = COALESCE(excluded.email, subjects.email),
    display_name = COALESCE(excluded.display_name, subjects.display_name),
    account_binding_id = COALESCE(excluded.account_binding_id, subjects.account_binding_id),
    account_binding_claim = COALESCE(excluded.account_binding_claim, subjects.account_binding_claim),
    last_synced_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
`

type EdgeUpsertSubjectParams struct {
	SubjectSub          string      `db:"subject_sub" json:"subject_sub"`
	SubjectKey          string      `db:"subject_key" json:"subject_key"`
	PreferredUsername   interface{} `db:"preferred_username" json:"preferred_username"`
	Email               interface{} `db:"email" json:"email"`
	DisplayName         interface{} `db:"display_name" json:"display_name"`
	AccountBindingID    interface{} `db:"account_binding_id" json:"account_binding_id"`
	AccountBindingClaim interface{} `db:"account_binding_claim" json:"account_binding_claim"`
}

// EdgeUpsertSubject
//
//	INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, created_at, updated_at)
//	VALUES (?1, ?2, NULLIF(?3, ''), NULLIF(?4, ''), NULLIF(?5, ''), NULLIF(?6, ''), NULLIF(?7, ''), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
//	ON CONFLICT(subject_sub) DO UPDATE SET
//	    subject_key = excluded.subject_key,
//	    preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
//	    email = COALESCE(excluded.email, subjects.email),
//	    display_name = COALESCE(excluded.display_name, subjects.display_name),
//	    account_binding_id = COALESCE(excluded.account_binding_id, subjects.account_binding_id),
//	    account_binding_claim = COALESCE(excluded.account_binding_claim, subjects.account_binding_claim),
//	    last_synced_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) EdgeUpsertSubject(ctx context.Context, arg EdgeUpsertSubjectParams) error {
	_, err := q.db.ExecContext(ctx, EdgeUpsertSubject,
		arg.SubjectSub,
		arg.SubjectKey,
		arg.PreferredUsername,
		arg.Email,
		arg.DisplayName,
		arg.AccountBindingID,
		arg.AccountBindingClaim,
	)
	return err
}

const GetBrowserSession = `-- name: GetBrowserSession :one
SELECT claims, expires_at
FROM edge_browser_sessions
WHERE session_id = ?1
`

type GetBrowserSessionParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

type GetBrowserSessionRow struct {
	Claims    string `db:"claims" json:"claims"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
}

// GetBrowserSession
//
//	SELECT claims, expires_at
//	FROM edge_browser_sessions
//	WHERE session_id = ?1
func (q *Queries) GetBrowserSession(ctx context.Context, arg GetBrowserSessionParams) (GetBrowserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, GetBrowserSession, arg.SessionID)
	var i GetBrowserSessionRow
	err := row.Scan(&i.Claims, &i.ExpiresAt)
	return i, err
}

const GetDeviceAuthorizationByDeviceCodeHash = `-- name: GetDeviceAuthorizationByDeviceCodeHash :one
SELECT device_authorization_id,
       client_id,
       subject_sub,
       service_id,
       resource,
       scope,
       device_code_hash,
       user_code_hash,
       user_code_display,
       status,
       interval_seconds,
       last_poll_at,
       poll_count,
       approved_at,
       denied_at,
       expires_at,
       consumed_at,
       created_at,
       updated_at
FROM oauth_device_authorizations
WHERE device_code_hash = ?1
`

type GetDeviceAuthorizationByDeviceCodeHashParams struct {
	DeviceCodeHash string `db:"device_code_hash" json:"device_code_hash"`
}

// GetDeviceAuthorizationByDeviceCodeHash
//
//	SELECT device_authorization_id,
//	       client_id,
//	       subject_sub,
//	       service_id,
//	       resource,
//	       scope,
//	       device_code_hash,
//	       user_code_hash,
//	       user_code_display,
//	       status,
//	       interval_seconds,
//	       last_poll_at,
//	       poll_count,
//	       approved_at,
//	       denied_at,
//	       expires_at,
//	       consumed_at,
//	       created_at,
//	       updated_at
//	FROM oauth_device_authorizations
//	WHERE device_code_hash = ?1
func (q *Queries) GetDeviceAuthorizationByDeviceCodeHash(ctx context.Context, arg GetDeviceAuthorizationByDeviceCodeHashParams) (OauthDeviceAuthorization, error) {
	row := q.db.QueryRowContext(ctx, GetDeviceAuthorizationByDeviceCodeHash, arg.DeviceCodeHash)
	var i OauthDeviceAuthorization
	err := row.Scan(
		&i.DeviceAuthorizationID,
		&i.ClientID,
		&i.SubjectSub,
		&i.ServiceID,
		&i.Resource,
		&i.Scope,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.UserCodeDisplay,
		&i.Status,
		&i.IntervalSeconds,
		&i.LastPollAt,
		&i.PollCount,
		&i.ApprovedAt,
		&i.DeniedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDeviceAuthorizationByUserCodeHash = `-- name: GetDeviceAuthorizationByUserCodeHash :one
SELECT device_authorization_id,
       client_id,
       subject_sub,
       service_id,
       resource,
       scope,
       device_code_hash,
       user_code_hash,
       user_code_display,
       status,
       interval_seconds,
       last_poll_at,
       poll_count,
       approved_at,
       denied_at,
       expires_at,
       consumed_at,
       created_at,
       updated_at
FROM oauth_device_authorizations
WHERE user_code_hash = ?1
`

type GetDeviceAuthorizationByUserCodeHashParams struct {
	UserCodeHash string `db:"user_code_hash" json:"user_code_hash"`
}

// GetDeviceAuthorizationByUserCodeHash
//
//	SELECT device_authorization_id,
//	       client_id,
//	       subject_sub,
//	       service_id,
//	       resource,
//	       scope,
//	       device_code_hash,
//	       user_code_hash,
//	       user_code_display,
//	       status,
//	       interval_seconds,
//	       last_poll_at,
//	       poll_count,
//	       approved_at,
//	       denied_at,
//	       expires_at,
//	       consumed_at,
//	       created_at,
//	       updated_at
//	FROM oauth_device_authorizations
//	WHERE user_code_hash = ?1
func (q *Queries) GetDeviceAuthorizationByUserCodeHash(ctx context.Context, arg GetDeviceAuthorizationByUserCodeHashParams) (OauthDeviceAuthorization, error) {
	row := q.db.QueryRowContext(ctx, GetDeviceAuthorizationByUserCodeHash, arg.UserCodeHash)
	var i OauthDeviceAuthorization
	err := row.Scan(
		&i.DeviceAuthorizationID,
		&i.ClientID,
		&i.SubjectSub,
		&i.ServiceID,
		&i.Resource,
		&i.Scope,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.UserCodeDisplay,
		&i.Status,
		&i.IntervalSeconds,
		&i.LastPollAt,
		&i.PollCount,
		&i.ApprovedAt,
		&i.DeniedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOAuthClient = `-- name: GetOAuthClient :one
SELECT redirect_uris, grant_types, scopes, created_by_subject_sub, token_endpoint_auth_method, client_secret_hash, disabled_at
FROM oauth_clients
WHERE client_id = ?1
`

type GetOAuthClientParams struct {
	ClientID string `db:"client_id" json:"client_id"`
}

type GetOAuthClientRow struct {
	RedirectUris            string         `db:"redirect_uris" json:"redirect_uris"`
	GrantTypes              string         `db:"grant_types" json:"grant_types"`
	Scopes                  string         `db:"scopes" json:"scopes"`
	CreatedBySubjectSub     sql.NullString `db:"created_by_subject_sub" json:"created_by_subject_sub"`
	TokenEndpointAuthMethod string         `db:"token_endpoint_auth_method" json:"token_endpoint_auth_method"`
	ClientSecretHash        sql.NullString `db:"client_secret_hash" json:"client_secret_hash"`
	DisabledAt              sql.NullString `db:"disabled_at" json:"disabled_at"`
}

// GetOAuthClient
//
//	SELECT redirect_uris, grant_types, scopes, created_by_subject_sub, token_endpoint_auth_method, client_secret_hash, disabled_at
//	FROM oauth_clients
//	WHERE client_id = ?1
func (q *Queries) GetOAuthClient(ctx context.Context, arg GetOAuthClientParams) (GetOAuthClientRow, error) {
	row := q.db.QueryRowContext(ctx, GetOAuthClient, arg.ClientID)
	var i GetOAuthClientRow
	err := row.Scan(
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.CreatedBySubjectSub,
		&i.TokenEndpointAuthMethod,
		&i.ClientSecretHash,
		&i.DisabledAt,
	)
	return i, err
}

const GetOAuthSessionByAccessHash = `-- name: GetOAuthSessionByAccessHash :one
SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
FROM oauth_sessions
WHERE access_token_hash = ?1
`

type GetOAuthSessionByAccessHashParams struct {
	AccessTokenHash sql.NullString `db:"access_token_hash" json:"access_token_hash"`
}

type GetOAuthSessionByAccessHashRow struct {
	SessionID                   []byte         `db:"session_id" json:"session_id"`
	SubjectSub                  sql.NullString `db:"subject_sub" json:"subject_sub"`
	ClientID                    string         `db:"client_id" json:"client_id"`
	ServiceID                   sql.NullString `db:"service_id" json:"service_id"`
	Resource                    string         `db:"resource" json:"resource"`
	RedirectUri                 string         `db:"redirect_uri" json:"redirect_uri"`
	Scope                       string         `db:"scope" json:"scope"`
	CodeChallenge               sql.NullString `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod         sql.NullString `db:"code_challenge_method" json:"code_challenge_method"`
	AuthorizationCodeHash       sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
	AuthorizationCodeCiphertext []byte         `db:"authorization_code_ciphertext" json:"authorization_code_ciphertext"`
	AccessTokenHash             sql.NullString `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenCiphertext       []byte         `db:"access_token_ciphertext" json:"access_token_ciphertext"`
	RefreshTokenHash            sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenCiphertext      []byte         `db:"refresh_token_ciphertext" json:"refresh_token_ciphertext"`
	CodeCreateAt                sql.NullString `db:"code_create_at" json:"code_create_at"`
	CodeExpiresInSeconds        int64          `db:"code_expires_in_seconds" json:"code_expires_in_seconds"`
	AccessCreateAt              sql.NullString `db:"access_create_at" json:"access_create_at"`
	AccessExpiresInSeconds      int64          `db:"access_expires_in_seconds" json:"access_expires_in_seconds"`
	RefreshCreateAt             sql.NullString `db:"refresh_create_at" json:"refresh_create_at"`
	RefreshExpiresInSeconds     int64          `db:"refresh_expires_in_seconds" json:"refresh_expires_in_seconds"`
	ExpiresAt                   sql.NullString `db:"expires_at" json:"expires_at"`
	IssuedVia                   string         `db:"issued_via" json:"issued_via"`
	OperatorReason              sql.NullString `db:"operator_reason" json:"operator_reason"`
}

// GetOAuthSessionByAccessHash
//
//	SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
//	FROM oauth_sessions
//	WHERE access_token_hash = ?1
func (q *Queries) GetOAuthSessionByAccessHash(ctx context.Context, arg GetOAuthSessionByAccessHashParams) (GetOAuthSessionByAccessHashRow, error) {
	row := q.db.QueryRowContext(ctx, GetOAuthSessionByAccessHash, arg.AccessTokenHash)
	var i GetOAuthSessionByAccessHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SubjectSub,
		&i.ClientID,
		&i.ServiceID,
		&i.Resource,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthorizationCodeHash,
		&i.AuthorizationCodeCiphertext,
		&i.AccessTokenHash,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenHash,
		&i.RefreshTokenCiphertext,
		&i.CodeCreateAt,
		&i.CodeExpiresInSeconds,
		&i.AccessCreateAt,
		&i.AccessExpiresInSeconds,
		&i.RefreshCreateAt,
		&i.RefreshExpiresInSeconds,
		&i.ExpiresAt,
		&i.IssuedVia,
		&i.OperatorReason,
	)
	return i, err
}

const GetOAuthSessionByCodeHash = `-- name: GetOAuthSessionByCodeHash :one
SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
FROM oauth_sessions
WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
`

type GetOAuthSessionByCodeHashParams struct {
	AuthorizationCodeHash sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
}

type GetOAuthSessionByCodeHashRow struct {
	SessionID                   []byte         `db:"session_id" json:"session_id"`
	SubjectSub                  sql.NullString `db:"subject_sub" json:"subject_sub"`
	ClientID                    string         `db:"client_id" json:"client_id"`
	ServiceID                   sql.NullString `db:"service_id" json:"service_id"`
	Resource                    string         `db:"resource" json:"resource"`
	RedirectUri                 string         `db:"redirect_uri" json:"redirect_uri"`
	Scope                       string         `db:"scope" json:"scope"`
	CodeChallenge               sql.NullString `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod         sql.NullString `db:"code_challenge_method" json:"code_challenge_method"`
	AuthorizationCodeHash       sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
	AuthorizationCodeCiphertext []byte         `db:"authorization_code_ciphertext" json:"authorization_code_ciphertext"`
	AccessTokenHash             sql.NullString `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenCiphertext       []byte         `db:"access_token_ciphertext" json:"access_token_ciphertext"`
	RefreshTokenHash            sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenCiphertext      []byte         `db:"refresh_token_ciphertext" json:"refresh_token_ciphertext"`
	CodeCreateAt                sql.NullString `db:"code_create_at" json:"code_create_at"`
	CodeExpiresInSeconds        int64          `db:"code_expires_in_seconds" json:"code_expires_in_seconds"`
	AccessCreateAt              sql.NullString `db:"access_create_at" json:"access_create_at"`
	AccessExpiresInSeconds      int64          `db:"access_expires_in_seconds" json:"access_expires_in_seconds"`
	RefreshCreateAt             sql.NullString `db:"refresh_create_at" json:"refresh_create_at"`
	RefreshExpiresInSeconds     int64          `db:"refresh_expires_in_seconds" json:"refresh_expires_in_seconds"`
	ExpiresAt                   sql.NullString `db:"expires_at" json:"expires_at"`
	IssuedVia                   string         `db:"issued_via" json:"issued_via"`
	OperatorReason              sql.NullString `db:"operator_reason" json:"operator_reason"`
}

// GetOAuthSessionByCodeHash
//
//	SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
//	FROM oauth_sessions
//	WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
func (q *Queries) GetOAuthSessionByCodeHash(ctx context.Context, arg GetOAuthSessionByCodeHashParams) (GetOAuthSessionByCodeHashRow, error) {
	row := q.db.QueryRowContext(ctx, GetOAuthSessionByCodeHash, arg.AuthorizationCodeHash)
	var i GetOAuthSessionByCodeHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SubjectSub,
		&i.ClientID,
		&i.ServiceID,
		&i.Resource,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthorizationCodeHash,
		&i.AuthorizationCodeCiphertext,
		&i.AccessTokenHash,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenHash,
		&i.RefreshTokenCiphertext,
		&i.CodeCreateAt,
		&i.CodeExpiresInSeconds,
		&i.AccessCreateAt,
		&i.AccessExpiresInSeconds,
		&i.RefreshCreateAt,
		&i.RefreshExpiresInSeconds,
		&i.ExpiresAt,
		&i.IssuedVia,
		&i.OperatorReason,
	)
	return i, err
}

const GetOAuthSessionByRefreshHash = `-- name: GetOAuthSessionByRefreshHash :one
SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
FROM oauth_sessions
WHERE refresh_token_hash = ?1
`

type GetOAuthSessionByRefreshHashParams struct {
	RefreshTokenHash sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
}

type GetOAuthSessionByRefreshHashRow struct {
	SessionID                   []byte         `db:"session_id" json:"session_id"`
	SubjectSub                  sql.NullString `db:"subject_sub" json:"subject_sub"`
	ClientID                    string         `db:"client_id" json:"client_id"`
	ServiceID                   sql.NullString `db:"service_id" json:"service_id"`
	Resource                    string         `db:"resource" json:"resource"`
	RedirectUri                 string         `db:"redirect_uri" json:"redirect_uri"`
	Scope                       string         `db:"scope" json:"scope"`
	CodeChallenge               sql.NullString `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod         sql.NullString `db:"code_challenge_method" json:"code_challenge_method"`
	AuthorizationCodeHash       sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
	AuthorizationCodeCiphertext []byte         `db:"authorization_code_ciphertext" json:"authorization_code_ciphertext"`
	AccessTokenHash             sql.NullString `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenCiphertext       []byte         `db:"access_token_ciphertext" json:"access_token_ciphertext"`
	RefreshTokenHash            sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenCiphertext      []byte         `db:"refresh_token_ciphertext" json:"refresh_token_ciphertext"`
	CodeCreateAt                sql.NullString `db:"code_create_at" json:"code_create_at"`
	CodeExpiresInSeconds        int64          `db:"code_expires_in_seconds" json:"code_expires_in_seconds"`
	AccessCreateAt              sql.NullString `db:"access_create_at" json:"access_create_at"`
	AccessExpiresInSeconds      int64          `db:"access_expires_in_seconds" json:"access_expires_in_seconds"`
	RefreshCreateAt             sql.NullString `db:"refresh_create_at" json:"refresh_create_at"`
	RefreshExpiresInSeconds     int64          `db:"refresh_expires_in_seconds" json:"refresh_expires_in_seconds"`
	ExpiresAt                   sql.NullString `db:"expires_at" json:"expires_at"`
	IssuedVia                   string         `db:"issued_via" json:"issued_via"`
	OperatorReason              sql.NullString `db:"operator_reason" json:"operator_reason"`
}

// GetOAuthSessionByRefreshHash
//
//	SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason
//	FROM oauth_sessions
//	WHERE refresh_token_hash = ?1
func (q *Queries) GetOAuthSessionByRefreshHash(ctx context.Context, arg GetOAuthSessionByRefreshHashParams) (GetOAuthSessionByRefreshHashRow, error) {
	row := q.db.QueryRowContext(ctx, GetOAuthSessionByRefreshHash, arg.RefreshTokenHash)
	var i GetOAuthSessionByRefreshHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SubjectSub,
		&i.ClientID,
		&i.ServiceID,
		&i.Resource,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthorizationCodeHash,
		&i.AuthorizationCodeCiphertext,
		&i.AccessTokenHash,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenHash,
		&i.RefreshTokenCiphertext,
		&i.CodeCreateAt,
		&i.CodeExpiresInSeconds,
		&i.AccessCreateAt,
		&i.AccessExpiresInSeconds,
		&i.RefreshCreateAt,
		&i.RefreshExpiresInSeconds,
		&i.ExpiresAt,
		&i.IssuedVia,
		&i.OperatorReason,
	)
	return i, err
}

const GetPendingLogin = `-- name: GetPendingLogin :one
SELECT state, return_to, nonce, expires_at
FROM edge_pending_logins
WHERE state = ?1
`

type GetPendingLoginParams struct {
	State string `db:"state" json:"state"`
}

type GetPendingLoginRow struct {
	State     string `db:"state" json:"state"`
	ReturnTo  string `db:"return_to" json:"return_to"`
	Nonce     string `db:"nonce" json:"nonce"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
}

// GetPendingLogin
//
//	SELECT state, return_to, nonce, expires_at
//	FROM edge_pending_logins
//	WHERE state = ?1
func (q *Queries) GetPendingLogin(ctx context.Context, arg GetPendingLoginParams) (GetPendingLoginRow, error) {
	row := q.db.QueryRowContext(ctx, GetPendingLogin, arg.State)
	var i GetPendingLoginRow
	err := row.Scan(
		&i.State,
		&i.ReturnTo,
		&i.Nonce,
		&i.ExpiresAt,
	)
	return i, err
}

const GetTenantUpstream = `-- name: GetTenantUpstream :one
SELECT COALESCE(upstream_url, '') AS upstream_url,
       internal_dns_name,
       desired_state,
       runtime_state,
       metadata
FROM tenant_instances
WHERE subject_sub = ?1
  AND service_id = ?2
`

type GetTenantUpstreamParams struct {
	SubjectSub string `db:"subject_sub" json:"subject_sub"`
	ServiceID  string `db:"service_id" json:"service_id"`
}

type GetTenantUpstreamRow struct {
	UpstreamUrl     string `db:"upstream_url" json:"upstream_url"`
	InternalDnsName string `db:"internal_dns_name" json:"internal_dns_name"`
	DesiredState    string `db:"desired_state" json:"desired_state"`
	RuntimeState    string `db:"runtime_state" json:"runtime_state"`
	Metadata        string `db:"metadata" json:"metadata"`
}

// GetTenantUpstream
//
//	SELECT COALESCE(upstream_url, '') AS upstream_url,
//	       internal_dns_name,
//	       desired_state,
//	       runtime_state,
//	       metadata
//	FROM tenant_instances
//	WHERE subject_sub = ?1
//	  AND service_id = ?2
func (q *Queries) GetTenantUpstream(ctx context.Context, arg GetTenantUpstreamParams) (GetTenantUpstreamRow, error) {
	row := q.db.QueryRowContext(ctx, GetTenantUpstream, arg.SubjectSub, arg.ServiceID)
	var i GetTenantUpstreamRow
	err := row.Scan(
		&i.UpstreamUrl,
		&i.InternalDnsName,
		&i.DesiredState,
		&i.RuntimeState,
		&i.Metadata,
	)
	return i, err
}

const InsertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (event_id, correlation_id, actor_subject_sub, service_id, event_type, event_status, payload)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertAuditEventParams struct {
	EventID         []byte         `db:"event_id" json:"event_id"`
	CorrelationID   string         `db:"correlation_id" json:"correlation_id"`
	ActorSubjectSub sql.NullString `db:"actor_subject_sub" json:"actor_subject_sub"`
	ServiceID       sql.NullString `db:"service_id" json:"service_id"`
	EventType       string         `db:"event_type" json:"event_type"`
	EventStatus     string         `db:"event_status" json:"event_status"`
	Payload         string         `db:"payload" json:"payload"`
}

// InsertAuditEvent
//
//	INSERT INTO audit_events (event_id, correlation_id, actor_subject_sub, service_id, event_type, event_status, payload)
//	VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, InsertAuditEvent,
		arg.EventID,
		arg.CorrelationID,
		arg.ActorSubjectSub,
		arg.ServiceID,
		arg.EventType,
		arg.EventStatus,
		arg.Payload,
	)
	return err
}

const MarkExpiredDeviceAuthorizations = `-- name: MarkExpiredDeviceAuthorizations :execrows
UPDATE oauth_device_authorizations
SET status = 'expired',
    updated_at = ?1
WHERE status IN ('pending', 'approved')
  AND expires_at <= ?1
`

type MarkExpiredDeviceAuthorizationsParams struct {
	Now string `db:"now" json:"now"`
}

// MarkExpiredDeviceAuthorizations
//
//	UPDATE oauth_device_authorizations
//	SET status = 'expired',
//	    updated_at = ?1
//	WHERE status IN ('pending', 'approved')
//	  AND expires_at <= ?1
func (q *Queries) MarkExpiredDeviceAuthorizations(ctx context.Context, arg MarkExpiredDeviceAuthorizationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, MarkExpiredDeviceAuthorizations, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const PruneExpiredDeviceAuthorizations = `-- name: PruneExpiredDeviceAuthorizations :execrows
DELETE FROM oauth_device_authorizations
WHERE status IN ('expired', 'denied', 'consumed')
  AND updated_at <= ?1
`

type PruneExpiredDeviceAuthorizationsParams struct {
	Cutoff string `db:"cutoff" json:"cutoff"`
}

// PruneExpiredDeviceAuthorizations
//
//	DELETE FROM oauth_device_authorizations
//	WHERE status IN ('expired', 'denied', 'consumed')
//	  AND updated_at <= ?1
func (q *Queries) PruneExpiredDeviceAuthorizations(ctx context.Context, arg PruneExpiredDeviceAuthorizationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, PruneExpiredDeviceAuthorizations, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const PutBrowserSession = `-- name: PutBrowserSession :exec
INSERT INTO edge_browser_sessions (session_id, subject_sub, claims, expires_at, updated_at)
VALUES (?1, NULLIF(?2, ''), ?3, ?4, CURRENT_TIMESTAMP)
ON CONFLICT(session_id) DO UPDATE SET subject_sub = excluded.subject_sub, claims = excluded.claims, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
`

type PutBrowserSessionParams struct {
	SessionID  string      `db:"session_id" json:"session_id"`
	SubjectSub interface{} `db:"subject_sub" json:"subject_sub"`
	Claims     string      `db:"claims" json:"claims"`
	ExpiresAt  string      `db:"expires_at" json:"expires_at"`
}

// PutBrowserSession
//
//	INSERT INTO edge_browser_sessions (session_id, subject_sub, claims, expires_at, updated_at)
//	VALUES (?1, NULLIF(?2, ''), ?3, ?4, CURRENT_TIMESTAMP)
//	ON CONFLICT(session_id) DO UPDATE SET subject_sub = excluded.subject_sub, claims = excluded.claims, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
func (q *Queries) PutBrowserSession(ctx context.Context, arg PutBrowserSessionParams) error {
	_, err := q.db.ExecContext(ctx, PutBrowserSession,
		arg.SessionID,
		arg.SubjectSub,
		arg.Claims,
		arg.ExpiresAt,
	)
	return err
}

const PutPendingLogin = `-- name: PutPendingLogin :exec
INSERT INTO edge_pending_logins (state, return_to, nonce, expires_at, updated_at)
VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
ON CONFLICT(state) DO UPDATE SET return_to = excluded.return_to, nonce = excluded.nonce, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
`

type PutPendingLoginParams struct {
	State     string `db:"state" json:"state"`
	ReturnTo  string `db:"return_to" json:"return_to"`
	Nonce     string `db:"nonce" json:"nonce"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
}

// PutPendingLogin
//
//	INSERT INTO edge_pending_logins (state, return_to, nonce, expires_at, updated_at)
//	VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
//	ON CONFLICT(state) DO UPDATE SET return_to = excluded.return_to, nonce = excluded.nonce, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
func (q *Queries) PutPendingLogin(ctx context.Context, arg PutPendingLoginParams) error {
	_, err := q.db.ExecContext(ctx, PutPendingLogin,
		arg.State,
		arg.ReturnTo,
		arg.Nonce,
		arg.ExpiresAt,
	)
	return err
}

const SlowDownDeviceAuthorizationPoll = `-- name: SlowDownDeviceAuthorizationPoll :execrows
UPDATE oauth_device_authorizations
SET last_poll_at = ?1,
    poll_count = poll_count + 1,
    interval_seconds = interval_seconds + ?2,
    updated_at = ?1
WHERE device_authorization_id = ?3
`

type SlowDownDeviceAuthorizationPollParams struct {
	LastPollAt            sql.NullString `db:"last_poll_at" json:"last_poll_at"`
	IncrementSeconds      int64          `db:"increment_seconds" json:"increment_seconds"`
	DeviceAuthorizationID []byte         `db:"device_authorization_id" json:"device_authorization_id"`
}

// SlowDownDeviceAuthorizationPoll
//
//	UPDATE oauth_device_authorizations
//	SET last_poll_at = ?1,
//	    poll_count = poll_count + 1,
//	    interval_seconds = interval_seconds + ?2,
//	    updated_at = ?1
//	WHERE device_authorization_id = ?3
func (q *Queries) SlowDownDeviceAuthorizationPoll(ctx context.Context, arg SlowDownDeviceAuthorizationPollParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SlowDownDeviceAuthorizationPoll, arg.LastPollAt, arg.IncrementSeconds, arg.DeviceAuthorizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateDeviceAuthorizationPoll = `-- name: UpdateDeviceAuthorizationPoll :execrows
UPDATE oauth_device_authorizations
SET last_poll_at = ?1,
    poll_count = poll_count + 1,
    updated_at = ?1
WHERE device_authorization_id = ?2
`

type UpdateDeviceAuthorizationPollParams struct {
	LastPollAt            sql.NullString `db:"last_poll_at" json:"last_poll_at"`
	DeviceAuthorizationID []byte         `db:"device_authorization_id" json:"device_authorization_id"`
}

// UpdateDeviceAuthorizationPoll
//
//	UPDATE oauth_device_authorizations
//	SET last_poll_at = ?1,
//	    poll_count = poll_count + 1,
//	    updated_at = ?1
//	WHERE device_authorization_id = ?2
func (q *Queries) UpdateDeviceAuthorizationPoll(ctx context.Context, arg UpdateDeviceAuthorizationPollParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateDeviceAuthorizationPoll, arg.LastPollAt, arg.DeviceAuthorizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpsertOAuthSession = `-- name: UpsertOAuthSession :exec
INSERT INTO oauth_sessions (session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, consumed_at, updated_at)
VALUES (?1, NULLIF(?2, ''), ?3, NULLIF(?4, ''), ?5, ?6, ?7, NULLIF(?8, ''), NULLIF(?9, ''), ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, NULL, CURRENT_TIMESTAMP)
ON CONFLICT(session_id) DO UPDATE SET
    subject_sub = excluded.subject_sub,
    client_id = excluded.client_id,
    service_id = excluded.service_id,
    resource = excluded.resource,
    redirect_uri = excluded.redirect_uri,
    scope = excluded.scope,
    code_challenge = excluded.code_challenge,
    code_challenge_method = excluded.code_challenge_method,
    authorization_code_hash = excluded.authorization_code_hash,
    authorization_code_ciphertext = excluded.authorization_code_ciphertext,
    access_token_hash = excluded.access_token_hash,
    access_token_ciphertext = excluded.access_token_ciphertext,
    refresh_token_hash = excluded.refresh_token_hash,
    refresh_token_ciphertext = excluded.refresh_token_ciphertext,
    code_create_at = excluded.code_create_at,
    code_expires_in_seconds = excluded.code_expires_in_seconds,
    access_create_at = excluded.access_create_at,
    access_expires_in_seconds = excluded.access_expires_in_seconds,
    refresh_create_at = excluded.refresh_create_at,
    refresh_expires_in_seconds = excluded.refresh_expires_in_seconds,
    expires_at = excluded.expires_at,
    issued_via = excluded.issued_via,
    operator_reason = excluded.operator_reason,
    consumed_at = NULL,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertOAuthSessionParams struct {
	SessionID                   []byte         `db:"session_id" json:"session_id"`
	SubjectSub                  interface{}    `db:"subject_sub" json:"subject_sub"`
	ClientID                    string         `db:"client_id" json:"client_id"`
	ServiceID                   interface{}    `db:"service_id" json:"service_id"`
	Resource                    string         `db:"resource" json:"resource"`
	RedirectUri                 string         `db:"redirect_uri" json:"redirect_uri"`
	Scope                       string         `db:"scope" json:"scope"`
	CodeChallenge               interface{}    `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod         interface{}    `db:"code_challenge_method" json:"code_challenge_method"`
	AuthorizationCodeHash       sql.NullString `db:"authorization_code_hash" json:"authorization_code_hash"`
	AuthorizationCodeCiphertext []byte         `db:"authorization_code_ciphertext" json:"authorization_code_ciphertext"`
	AccessTokenHash             sql.NullString `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenCiphertext       []byte         `db:"access_token_ciphertext" json:"access_token_ciphertext"`
	RefreshTokenHash            sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenCiphertext      []byte         `db:"refresh_token_ciphertext" json:"refresh_token_ciphertext"`
	CodeCreateAt                sql.NullString `db:"code_create_at" json:"code_create_at"`
	CodeExpiresInSeconds        int64          `db:"code_expires_in_seconds" json:"code_expires_in_seconds"`
	AccessCreateAt              sql.NullString `db:"access_create_at" json:"access_create_at"`
	AccessExpiresInSeconds      int64          `db:"access_expires_in_seconds" json:"access_expires_in_seconds"`
	RefreshCreateAt             sql.NullString `db:"refresh_create_at" json:"refresh_create_at"`
	RefreshExpiresInSeconds     int64          `db:"refresh_expires_in_seconds" json:"refresh_expires_in_seconds"`
	ExpiresAt                   sql.NullString `db:"expires_at" json:"expires_at"`
	IssuedVia                   string         `db:"issued_via" json:"issued_via"`
	OperatorReason              sql.NullString `db:"operator_reason" json:"operator_reason"`
}

// UpsertOAuthSession
//
//	INSERT INTO oauth_sessions (session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, consumed_at, updated_at)
//	VALUES (?1, NULLIF(?2, ''), ?3, NULLIF(?4, ''), ?5, ?6, ?7, NULLIF(?8, ''), NULLIF(?9, ''), ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, NULL, CURRENT_TIMESTAMP)
//	ON CONFLICT(session_id) DO UPDATE SET
//	    subject_sub = excluded.subject_sub,
//	    client_id = excluded.client_id,
//	    service_id = excluded.service_id,
//	    resource = excluded.resource,
//	    redirect_uri = excluded.redirect_uri,
//	    scope = excluded.scope,
//	    code_challenge = excluded.code_challenge,
//	    code_challenge_method = excluded.code_challenge_method,
//	    authorization_code_hash = excluded.authorization_code_hash,
//	    authorization_code_ciphertext = excluded.authorization_code_ciphertext,
//	    access_token_hash = excluded.access_token_hash,
//	    access_token_ciphertext = excluded.access_token_ciphertext,
//	    refresh_token_hash = excluded.refresh_token_hash,
//	    refresh_token_ciphertext = excluded.refresh_token_ciphertext,
//	    code_create_at = excluded.code_create_at,
//	    code_expires_in_seconds = excluded.code_expires_in_seconds,
//	    access_create_at = excluded.access_create_at,
//	    access_expires_in_seconds = excluded.access_expires_in_seconds,
//	    refresh_create_at = excluded.refresh_create_at,
//	    refresh_expires_in_seconds = excluded.refresh_expires_in_seconds,
//	    expires_at = excluded.expires_at,
//	    issued_via = excluded.issued_via,
//	    operator_reason = excluded.operator_reason,
//	    consumed_at = NULL,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertOAuthSession(ctx context.Context, arg UpsertOAuthSessionParams) error {
	_, err := q.db.ExecContext(ctx, UpsertOAuthSession,
		arg.SessionID,
		arg.SubjectSub,
		arg.ClientID,
		arg.ServiceID,
		arg.Resource,
		arg.RedirectUri,
		arg.Scope,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.AuthorizationCodeHash,
		arg.AuthorizationCodeCiphertext,
		arg.AccessTokenHash,
		arg.AccessTokenCiphertext,
		arg.RefreshTokenHash,
		arg.RefreshTokenCiphertext,
		arg.CodeCreateAt,
		arg.CodeExpiresInSeconds,
		arg.AccessCreateAt,
		arg.AccessExpiresInSeconds,
		arg.RefreshCreateAt,
		arg.RefreshExpiresInSeconds,
		arg.ExpiresAt,
		arg.IssuedVia,
		arg.OperatorReason,
	)
	return err
}
