// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leases.sql

package platformdb

import (
	"context"
)

const AcquireControlPlaneLease = `-- name: AcquireControlPlaneLease :one
INSERT INTO control_plane_leases (
    lease_name,
    holder_id,
    expires_at,
    updated_at
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
ON CONFLICT(lease_name) DO UPDATE SET
    holder_id = excluded.holder_id,
    expires_at = excluded.expires_at,
    updated_at = excluded.updated_at
WHERE control_plane_leases.holder_id = excluded.holder_id
    OR control_plane_leases.expires_at <= excluded.updated_at
RETURNING holder_id
`

type AcquireControlPlaneLeaseParams struct {
	LeaseName string `db:"lease_name" json:"lease_name"`
	HolderID  string `db:"holder_id" json:"holder_id"`
	ExpiresAt int64  `db:"expires_at" json:"expires_at"`
	Now       int64  `db:"now" json:"now"`
}

// AcquireControlPlaneLease
//
//	INSERT INTO control_plane_leases (
//	    lease_name,
//	    holder_id,
//	    expires_at,
//	    updated_at
//	)
//	VALUES (
//	    ?1,
//	    ?2,
//	    ?3,
//	    ?4
//	)
//	ON CONFLICT(lease_name) DO UPDATE SET
//	    holder_id = excluded.holder_id,
//	    expires_at = excluded.expires_at,
//	    updated_at = excluded.updated_at
//	WHERE control_plane_leases.holder_id = excluded.holder_id
//	    OR control_plane_leases.expires_at <= excluded.updated_at
//	RETURNING holder_id
func (q *Queries) AcquireControlPlaneLease(ctx context.Context, arg AcquireControlPlaneLeaseParams) (string, error) {
	row := q.db.QueryRowContext(ctx, AcquireControlPlaneLease,
		arg.LeaseName,
		arg.HolderID,
		arg.ExpiresAt,
		arg.Now,
	)
	var holder_id string
	err := row.Scan(&holder_id)
	return holder_id, err
}

const ReleaseControlPlaneLease = `-- name: ReleaseControlPlaneLease :exec
DELETE FROM control_plane_leases
WHERE lease_name = ?1
    AND holder_id = ?2
`

type ReleaseControlPlaneLeaseParams struct {
	LeaseName string `db:"lease_name" json:"lease_name"`
	HolderID  string `db:"holder_id" json:"holder_id"`
}

// ReleaseControlPlaneLease
//
//	DELETE FROM control_plane_leases
//	WHERE lease_name = ?1
//	    AND holder_id = ?2
func (q *Queries) ReleaseControlPlaneLease(ctx context.Context, arg ReleaseControlPlaneLeaseParams) error {
	_, err := q.db.ExecContext(ctx, ReleaseControlPlaneLease, arg.LeaseName, arg.HolderID)
	return err
}
