// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platformdb

import (
	"database/sql"
)

type TenantInstance struct {
	TenantID             []byte         `db:"tenant_id" json:"tenant_id"`
	SubjectSub           string         `db:"subject_sub" json:"subject_sub"`
	ServiceID            string         `db:"service_id" json:"service_id"`
	SubjectKey           string         `db:"subject_key" json:"subject_key"`
	TenantInstanceName   string         `db:"tenant_instance_name" json:"tenant_instance_name"`
	InternalDnsName      string         `db:"internal_dns_name" json:"internal_dns_name"`
	DesiredState         string         `db:"desired_state" json:"desired_state"`
	RuntimeState         string         `db:"runtime_state" json:"runtime_state"`
	CoolifyResourceID    sql.NullString `db:"coolify_resource_id" json:"coolify_resource_id"`
	CoolifyApplicationID sql.NullString `db:"coolify_application_id" json:"coolify_application_id"`
	UpstreamUrl          sql.NullString `db:"upstream_url" json:"upstream_url"`
	SecretVersion        sql.NullString `db:"secret_version" json:"secret_version"`
	LastHealthyAt        sql.NullString `db:"last_healthy_at" json:"last_healthy_at"`
	LastReconciledAt     sql.NullString `db:"last_reconciled_at" json:"last_reconciled_at"`
	LastError            sql.NullString `db:"last_error" json:"last_error"`
	Metadata             string         `db:"metadata" json:"metadata"`
	CreatedAt            string         `db:"created_at" json:"created_at"`
	UpdatedAt            string         `db:"updated_at" json:"updated_at"`
}
