// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platformdb

import (
	"context"
)

type Querier interface {
	//AcquireControlPlaneLease
	//
	//  INSERT INTO control_plane_leases (
	//      lease_name,
	//      holder_id,
	//      expires_at,
	//      updated_at
	//  )
	//  VALUES (
	//      ?1,
	//      ?2,
	//      ?3,
	//      ?4
	//  )
	//  ON CONFLICT(lease_name) DO UPDATE SET
	//      holder_id = excluded.holder_id,
	//      expires_at = excluded.expires_at,
	//      updated_at = excluded.updated_at
	//  WHERE control_plane_leases.holder_id = excluded.holder_id
	//      OR control_plane_leases.expires_at <= excluded.updated_at
	//  RETURNING holder_id
	AcquireControlPlaneLease(ctx context.Context, arg AcquireControlPlaneLeaseParams) (string, error)
	//AllowedServiceGrant
	//
	//  SELECT EXISTS (
	//      SELECT 1
	//      FROM service_grants
	//      JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//      WHERE service_grants.subject_sub = ?1
	//        AND service_grants.service_id = ?2
	//        AND service_catalog.enabled = 1
	//  ) AS allowed
	AllowedServiceGrant(ctx context.Context, arg AllowedServiceGrantParams) (int64, error)
	//ConsumeOAuthSessionByCodeHash
	//
	//  UPDATE oauth_sessions
	//  SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
	//  WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
	//  RETURNING session_id, subject_sub, client_id, service_id, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at
	ConsumeOAuthSessionByCodeHash(ctx context.Context, arg ConsumeOAuthSessionByCodeHashParams) (ConsumeOAuthSessionByCodeHashRow, error)
	//ConsumeOAuthSessionByRefreshHash
	//
	//  UPDATE oauth_sessions
	//  SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
	//  WHERE refresh_token_hash = ?1 AND consumed_at IS NULL
	//  RETURNING session_id, subject_sub, client_id, service_id, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at
	ConsumeOAuthSessionByRefreshHash(ctx context.Context, arg ConsumeOAuthSessionByRefreshHashParams) (ConsumeOAuthSessionByRefreshHashRow, error)
	//CountAllowedServiceGrants
	//
	//  SELECT COUNT(DISTINCT service_grants.service_id) AS allowed_count
	//  FROM service_grants
	//  JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//  WHERE service_grants.subject_sub = ?1
	//    AND service_catalog.enabled = 1
	//    AND service_grants.service_id IN (/*SLICE:service_ids*/?)
	CountAllowedServiceGrants(ctx context.Context, arg CountAllowedServiceGrantsParams) (int64, error)
	//CountAuditEventsByType
	//
	//  SELECT COUNT(*) AS audit_count
	//  FROM audit_events
	//  WHERE event_type = ?1
	CountAuditEventsByType(ctx context.Context, arg CountAuditEventsByTypeParams) (int64, error)
	//CreateOAuthClient
	//
	//  INSERT INTO oauth_clients (client_id, client_name, created_by_subject_sub, redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, client_secret_hash, metadata, created_at, updated_at)
	//  VALUES (?1, ?2, NULLIF(?3, ''), ?4, ?5, ?6, ?7, ?8, ?9, '{}', ?10, ?10)
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error
	//DeleteAllServiceGrants
	//
	//  DELETE FROM service_grants
	DeleteAllServiceGrants(ctx context.Context) error
	//DeleteBrowserSession
	//
	//  DELETE FROM edge_browser_sessions WHERE session_id = ?1
	DeleteBrowserSession(ctx context.Context, arg DeleteBrowserSessionParams) error
	//DeleteOAuthSessionByAccessHash
	//
	//  DELETE FROM oauth_sessions WHERE access_token_hash = ?1
	DeleteOAuthSessionByAccessHash(ctx context.Context, arg DeleteOAuthSessionByAccessHashParams) error
	//DeleteOAuthSessionByCodeHash
	//
	//  DELETE FROM oauth_sessions WHERE authorization_code_hash = ?1
	DeleteOAuthSessionByCodeHash(ctx context.Context, arg DeleteOAuthSessionByCodeHashParams) error
	//DeleteOAuthSessionByRefreshHash
	//
	//  DELETE FROM oauth_sessions WHERE refresh_token_hash = ?1
	DeleteOAuthSessionByRefreshHash(ctx context.Context, arg DeleteOAuthSessionByRefreshHashParams) error
	//DeletePendingLogin
	//
	//  DELETE FROM edge_pending_logins WHERE state = ?1
	DeletePendingLogin(ctx context.Context, arg DeletePendingLoginParams) error
	//DeleteStaleServiceGrants
	//
	//  DELETE FROM service_grants WHERE subject_sub NOT IN (/*SLICE:subject_subs*/?)
	DeleteStaleServiceGrants(ctx context.Context, arg DeleteStaleServiceGrantsParams) error
	//DeleteSubjectGrants
	//
	//  DELETE FROM service_grants WHERE subject_sub = ?1
	DeleteSubjectGrants(ctx context.Context, arg DeleteSubjectGrantsParams) error
	//DeleteTenantInstance
	//
	//  DELETE FROM tenant_instances WHERE tenant_id = ?1
	DeleteTenantInstance(ctx context.Context, arg DeleteTenantInstanceParams) error
	//DisableServiceCatalogEntriesNotIn
	//
	//  UPDATE service_catalog
	//  SET enabled = 0,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE service_id NOT IN (/*SLICE:service_ids*/?)
	DisableServiceCatalogEntriesNotIn(ctx context.Context, arg DisableServiceCatalogEntriesNotInParams) error
	//EdgeUpsertSubject
	//
	//  INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, last_synced_at, created_at, updated_at)
	//  VALUES (?1, ?2, NULLIF(?3, ''), NULLIF(?4, ''), NULLIF(?5, ''), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  ON CONFLICT(subject_sub) DO UPDATE SET
	//      subject_key = excluded.subject_key,
	//      preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
	//      email = COALESCE(excluded.email, subjects.email),
	//      display_name = COALESCE(excluded.display_name, subjects.display_name),
	//      last_synced_at = CURRENT_TIMESTAMP,
	//      updated_at = CURRENT_TIMESTAMP
	EdgeUpsertSubject(ctx context.Context, arg EdgeUpsertSubjectParams) error
	//EnableTenantInstance
	//
	//  UPDATE tenant_instances
	//  SET subject_key = ?1,
	//      tenant_instance_name = ?2,
	//      internal_dns_name = ?3,
	//      desired_state = ?4,
	//      runtime_state = ?5,
	//      last_error = NULLIF(?6, ''),
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?7
	EnableTenantInstance(ctx context.Context, arg EnableTenantInstanceParams) error
	//GetBrowserSession
	//
	//  SELECT claims, expires_at
	//  FROM edge_browser_sessions
	//  WHERE session_id = ?1
	GetBrowserSession(ctx context.Context, arg GetBrowserSessionParams) (GetBrowserSessionRow, error)
	//GetOAuthClient
	//
	//  SELECT redirect_uris, scopes, created_by_subject_sub, token_endpoint_auth_method, client_secret_hash, disabled_at
	//  FROM oauth_clients
	//  WHERE client_id = ?1
	GetOAuthClient(ctx context.Context, arg GetOAuthClientParams) (GetOAuthClientRow, error)
	//GetOAuthSessionByAccessHash
	//
	//  SELECT session_id, subject_sub, client_id, service_id, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at
	//  FROM oauth_sessions
	//  WHERE access_token_hash = ?1
	GetOAuthSessionByAccessHash(ctx context.Context, arg GetOAuthSessionByAccessHashParams) (GetOAuthSessionByAccessHashRow, error)
	//GetOAuthSessionByRefreshHash
	//
	//  SELECT session_id, subject_sub, client_id, service_id, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at
	//  FROM oauth_sessions
	//  WHERE refresh_token_hash = ?1
	GetOAuthSessionByRefreshHash(ctx context.Context, arg GetOAuthSessionByRefreshHashParams) (GetOAuthSessionByRefreshHashRow, error)
	//GetPendingLogin
	//
	//  SELECT state, return_to, nonce, expires_at
	//  FROM edge_pending_logins
	//  WHERE state = ?1
	GetPendingLogin(ctx context.Context, arg GetPendingLoginParams) (GetPendingLoginRow, error)
	//GetTenantUpstream
	//
	//  SELECT COALESCE(upstream_url, '') AS upstream_url,
	//         desired_state,
	//         runtime_state
	//  FROM tenant_instances
	//  WHERE subject_sub = ?1
	//    AND service_id = ?2
	GetTenantUpstream(ctx context.Context, arg GetTenantUpstreamParams) (GetTenantUpstreamRow, error)
	//InsertAuditEvent
	//
	//  INSERT INTO audit_events (event_id, correlation_id, actor_subject_sub, service_id, event_type, event_status, payload)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	//InsertReconcileRun
	//
	//  INSERT INTO reconcile_runs (run_id, tenant_id, desired_state, observed_state, action, status, details, started_at, finished_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
	InsertReconcileRun(ctx context.Context, arg InsertReconcileRunParams) error
	//InsertServiceGrant
	//
	//  INSERT INTO service_grants (subject_sub, service_id, source_group, granted_at, last_synced_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5)
	InsertServiceGrant(ctx context.Context, arg InsertServiceGrantParams) error
	//InsertTenantInstance
	//
	//  INSERT INTO tenant_instances (tenant_id, subject_sub, service_id, subject_key, tenant_instance_name, internal_dns_name, desired_state, runtime_state)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
	InsertTenantInstance(ctx context.Context, arg InsertTenantInstanceParams) error
	//ListDesiredTenantSpecs
	//
	//  SELECT subjects.subject_sub,
	//         subjects.subject_key,
	//         COALESCE(subjects.preferred_username, '') AS preferred_username,
	//         COALESCE(subjects.email, '') AS email,
	//         COALESCE(subjects.display_name, '') AS display_name,
	//         service_grants.service_id
	//  FROM service_grants
	//  JOIN subjects ON subjects.subject_sub = service_grants.subject_sub
	//  JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//  WHERE service_catalog.enabled = 1
	//  ORDER BY service_grants.service_id, subjects.subject_sub
	ListDesiredTenantSpecs(ctx context.Context) ([]ListDesiredTenantSpecsRow, error)
	//ListEnabledServiceCatalog
	//
	//  SELECT service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      enabled,
	//      created_at,
	//      updated_at
	//  FROM service_catalog
	//  WHERE enabled = 1
	//  ORDER BY service_id
	ListEnabledServiceCatalog(ctx context.Context) ([]ServiceCatalog, error)
	//ListTenantInstances
	//
	//  SELECT tenant_id,
	//         subject_sub,
	//         service_id,
	//         subject_key,
	//         tenant_instance_name,
	//         internal_dns_name,
	//         desired_state,
	//         runtime_state,
	//         coolify_resource_id,
	//         coolify_application_id,
	//         upstream_url,
	//         secret_version,
	//         last_healthy_at,
	//         last_reconciled_at,
	//         last_error,
	//         metadata,
	//         created_at,
	//         updated_at
	//  FROM tenant_instances
	//  ORDER BY service_id, subject_sub
	ListTenantInstances(ctx context.Context) ([]TenantInstance, error)
	//MarkTenantDesiredDeleted
	//
	//  UPDATE tenant_instances
	//  SET desired_state = ?1,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?2
	MarkTenantDesiredDeleted(ctx context.Context, arg MarkTenantDesiredDeletedParams) error
	//MarkTenantReconciled
	//
	//  UPDATE tenant_instances
	//  SET last_reconciled_at = ?1,
	//      last_error = NULLIF(?2, ''),
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?3
	MarkTenantReconciled(ctx context.Context, arg MarkTenantReconciledParams) error
	//PutBrowserSession
	//
	//  INSERT INTO edge_browser_sessions (session_id, subject_sub, claims, expires_at, updated_at)
	//  VALUES (?1, NULLIF(?2, ''), ?3, ?4, CURRENT_TIMESTAMP)
	//  ON CONFLICT(session_id) DO UPDATE SET subject_sub = excluded.subject_sub, claims = excluded.claims, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
	PutBrowserSession(ctx context.Context, arg PutBrowserSessionParams) error
	//PutPendingLogin
	//
	//  INSERT INTO edge_pending_logins (state, return_to, nonce, expires_at, updated_at)
	//  VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
	//  ON CONFLICT(state) DO UPDATE SET return_to = excluded.return_to, nonce = excluded.nonce, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
	PutPendingLogin(ctx context.Context, arg PutPendingLoginParams) error
	//ReleaseControlPlaneLease
	//
	//  DELETE FROM control_plane_leases
	//  WHERE lease_name = ?1
	//      AND holder_id = ?2
	ReleaseControlPlaneLease(ctx context.Context, arg ReleaseControlPlaneLeaseParams) error
	//UpdateTenantRuntimeStatus
	//
	//  UPDATE tenant_instances
	//  SET runtime_state = ?1,
	//      coolify_resource_id = CASE WHEN CAST(?2 AS boolean) THEN NULL WHEN ?3 = '' THEN coolify_resource_id ELSE ?3 END,
	//      coolify_application_id = CASE WHEN ?2 THEN NULL WHEN ?4 = '' THEN coolify_application_id ELSE ?4 END,
	//      upstream_url = CASE WHEN ?2 THEN NULL WHEN ?5 = '' THEN upstream_url ELSE ?5 END,
	//      last_healthy_at = CASE WHEN ?2 THEN NULL WHEN ?6 IS NULL THEN last_healthy_at ELSE ?6 END,
	//      last_error = NULLIF(?7, ''),
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?8
	UpdateTenantRuntimeStatus(ctx context.Context, arg UpdateTenantRuntimeStatusParams) error
	//UpsertOAuthSession
	//
	//  INSERT INTO oauth_sessions (session_id, subject_sub, client_id, service_id, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, consumed_at, updated_at)
	//  VALUES (?1, NULLIF(?2, ''), ?3, NULLIF(?4, ''), ?5, ?6, NULLIF(?7, ''), NULLIF(?8, ''), ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, NULL, CURRENT_TIMESTAMP)
	//  ON CONFLICT(session_id) DO UPDATE SET
	//      subject_sub = excluded.subject_sub,
	//      client_id = excluded.client_id,
	//      service_id = excluded.service_id,
	//      redirect_uri = excluded.redirect_uri,
	//      scope = excluded.scope,
	//      code_challenge = excluded.code_challenge,
	//      code_challenge_method = excluded.code_challenge_method,
	//      authorization_code_hash = excluded.authorization_code_hash,
	//      authorization_code_ciphertext = excluded.authorization_code_ciphertext,
	//      access_token_hash = excluded.access_token_hash,
	//      access_token_ciphertext = excluded.access_token_ciphertext,
	//      refresh_token_hash = excluded.refresh_token_hash,
	//      refresh_token_ciphertext = excluded.refresh_token_ciphertext,
	//      code_create_at = excluded.code_create_at,
	//      code_expires_in_seconds = excluded.code_expires_in_seconds,
	//      access_create_at = excluded.access_create_at,
	//      access_expires_in_seconds = excluded.access_expires_in_seconds,
	//      refresh_create_at = excluded.refresh_create_at,
	//      refresh_expires_in_seconds = excluded.refresh_expires_in_seconds,
	//      expires_at = excluded.expires_at,
	//      consumed_at = NULL,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertOAuthSession(ctx context.Context, arg UpsertOAuthSessionParams) error
	//UpsertServiceCatalogEntry
	//
	//  INSERT INTO service_catalog (
	//      service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      enabled,
	//      updated_at
	//  )
	//  VALUES (
	//      ?1,
	//      ?2,
	//      ?3,
	//      ?4,
	//      ?5,
	//      ?6,
	//      ?7,
	//      ?8,
	//      ?9,
	//      ?10,
	//      ?11,
	//      ?12,
	//      ?13,
	//      ?14,
	//      CURRENT_TIMESTAMP
	//  )
	//  ON CONFLICT(service_id) DO UPDATE SET
	//      display_name = excluded.display_name,
	//      upstream_service_name = excluded.upstream_service_name,
	//      transport_type = excluded.transport_type,
	//      internal_port = excluded.internal_port,
	//      public_path = excluded.public_path,
	//      internal_upstream_path = excluded.internal_upstream_path,
	//      health_path = excluded.health_path,
	//      health_probe_expectation = excluded.health_probe_expectation,
	//      resource_profile = excluded.resource_profile,
	//      persistence_policy = excluded.persistence_policy,
	//      adapter_requirement = excluded.adapter_requirement,
	//      enabled = excluded.enabled,
	//      secret_contract = excluded.secret_contract,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertServiceCatalogEntry(ctx context.Context, arg UpsertServiceCatalogEntryParams) error
	//UpsertSubject
	//
	//  INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, last_synced_at, updated_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  ON CONFLICT(subject_sub) DO UPDATE SET
	//      subject_key = excluded.subject_key,
	//      preferred_username = excluded.preferred_username,
	//      email = excluded.email,
	//      display_name = excluded.display_name,
	//      last_synced_at = CURRENT_TIMESTAMP,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertSubject(ctx context.Context, arg UpsertSubjectParams) error
}

var _ Querier = (*Queries)(nil)
